import type { AssessmentItem, StageAssessment } from '../types.js';

export const cognitiveTeal: StageAssessment = {
  line: 'Cognitive',
  stage: 'Teal',
  tasks: [
    {
      id: 'cog-teal-nback4',
      type: 'n_back',
      description: 'N=4+ n-back with high complexity',
      parameters: { n: 4, trials: 20, stimulusDurationMs: 800, interStimulusMs: 250, adaptive: true },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'cog-teal-systems',
      type: 'pattern_prediction',
      description: 'Complex systems prediction: multi-variable outcomes',
      parameters: { patternType: 'systems', variables: 4, trials: 8, feedbackDelay: true },
      measures: ['accuracy', 'complexity_handled', 'transfer'],
    },
    {
      id: 'cog-teal-meta-pattern',
      type: 'scenario',
      description: 'Meta-pattern recognition: patterns of patterns',
      parameters: { scenarioType: 'meta-pattern', levels: 2, responseType: 'text', scenarios: 3 },
      measures: ['depth', 'complexity_handled', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      complexity_handled: 0.3,
      self_correction: 0.2,
    },
  },
  minimumTrials: 5,
  estimatedDurationMs: 360000,
  itemPool: [
    { id: 'cognitive-teal-01', taskType: 'n_back', difficulty: 0.2, parameters: { n: 4, trials: 10, stimulusDurationMs: 1000, interStimulusMs: 400 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-teal-02', taskType: 'n_back', difficulty: 0.25, parameters: { n: 4, trials: 12, stimulusDurationMs: 950, interStimulusMs: 380 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-teal-03', taskType: 'n_back', difficulty: 0.3, parameters: { n: 5, trials: 8, stimulusDurationMs: 1000, interStimulusMs: 380 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-teal-04', taskType: 'pattern_prediction', difficulty: 0.35, parameters: { patternType: 'systems', variables: 3, trials: 6, feedbackDelay: true }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-teal-05', taskType: 'n_back', difficulty: 0.4, parameters: { n: 5, trials: 10, stimulusDurationMs: 950, interStimulusMs: 350 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-teal-06', taskType: 'pattern_prediction', difficulty: 0.4, parameters: { patternType: 'systems', variables: 4, trials: 6, feedbackDelay: true }, measures: ['accuracy', 'complexity_handled'] },
    { id: 'cognitive-teal-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'meta-pattern', levels: 2, responseType: 'text', scenarios: 2 }, measures: ['depth', 'complexity_handled'] },
    { id: 'cognitive-teal-08', taskType: 'n_back', difficulty: 0.5, parameters: { n: 5, trials: 14, stimulusDurationMs: 900, interStimulusMs: 300 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-teal-09', taskType: 'pattern_prediction', difficulty: 0.5, parameters: { patternType: 'paradox-resolution', variables: 4, trials: 4, contradictionPresent: true }, measures: ['accuracy', 'complexity_handled', 'coherence'] },
    { id: 'cognitive-teal-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'multi-system-integration', levels: 2, responseType: 'text', scenarios: 3, systemCount: 3 }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'cognitive-teal-11', taskType: 'n_back', difficulty: 0.55, parameters: { n: 5, trials: 16, stimulusDurationMs: 850, interStimulusMs: 280 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-teal-12', taskType: 'pattern_prediction', difficulty: 0.6, parameters: { patternType: 'systems', variables: 5, trials: 6, feedbackDelay: true, emergentProperties: true }, measures: ['accuracy', 'complexity_handled', 'transfer'] },
    { id: 'cognitive-teal-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'paradox-resolution', levels: 2, responseType: 'text', scenarios: 2, holdBothTruths: true }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'cognitive-teal-14', taskType: 'n_back', difficulty: 0.65, parameters: { n: 6, trials: 10, stimulusDurationMs: 900, interStimulusMs: 300 }, measures: ['accuracy', 'response_time'] },
    { id: 'cognitive-teal-15', taskType: 'pattern_prediction', difficulty: 0.7, parameters: { patternType: 'multi-system-integration', variables: 5, trials: 6, emergentProperties: true }, measures: ['accuracy', 'complexity_handled', 'transfer'] },
    { id: 'cognitive-teal-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'meta-pattern', levels: 3, responseType: 'text', scenarios: 2, systemCount: 4 }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'cognitive-teal-17', taskType: 'n_back', difficulty: 0.8, parameters: { n: 6, trials: 14, stimulusDurationMs: 850, interStimulusMs: 280 }, measures: ['accuracy', 'response_time', 'consistency'] },
    { id: 'cognitive-teal-18', taskType: 'pattern_prediction', difficulty: 0.8, parameters: { patternType: 'paradox-resolution', variables: 6, trials: 6, contradictionPresent: true, multiLevel: true }, measures: ['accuracy', 'complexity_handled', 'coherence'] },
    { id: 'cognitive-teal-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'multi-system-integration', levels: 3, responseType: 'text', scenarios: 3, systemCount: 5 }, measures: ['depth', 'complexity_handled', 'transfer'] },
    { id: 'cognitive-teal-20', taskType: 'n_back', difficulty: 0.9, parameters: { n: 6, trials: 18, stimulusDurationMs: 800, interStimulusMs: 260, adaptive: true }, measures: ['accuracy', 'response_time', 'consistency', 'complexity_handled'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Identify meta-pattern independently',
      task: {
        id: 'cog-teal-probe-agency',
        type: 'scenario',
        description: 'Identify patterns of patterns without guidance',
        parameters: { scenarioType: 'meta-pattern', levels: 2, responseType: 'text', soloMode: true },
        measures: ['depth', 'complexity_handled'],
      },
      healthyResponse: 'Sees meta-patterns with independent clarity',
      addictionSignal: 'Sees patterns everywhere, cannot stop analyzing',
      allergySignal: 'Cannot see meta-patterns without guidance',
    },
    communion: {
      description: 'Help NPC see system-level pattern',
      task: {
        id: 'cog-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'Help NPC understand a system-level pattern',
        parameters: { prompt: 'I see the parts but not how they connect. What am I missing?', maxResponseLength: 500 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Guides other toward systems-seeing with patience',
      addictionSignal: 'Forces systems-view on others not ready',
      allergySignal: 'Cannot share systems-level perception',
    },
    eros: {
      description: 'Attempt n=5 and 3-level meta-pattern',
      task: {
        id: 'cog-teal-probe-eros',
        type: 'n_back',
        description: 'N-back at n=5 with maximum complexity',
        parameters: { n: 5, trials: 10, stimulusDurationMs: 750, interStimulusMs: 250 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Reaches toward highest cognitive integration',
      addictionSignal: 'Compulsive complexity-seeking, cannot rest',
      allergySignal: 'Refuses growth at this level',
    },
    agape: {
      description: 'Return to n=2 with full presence and ease',
      task: {
        id: 'cog-teal-probe-agape',
        type: 'n_back',
        description: 'Return to n=2 with full ease',
        parameters: { n: 2, trials: 6, stimulusDurationMs: 1200, interStimulusMs: 500 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simplicity with grace and presence',
      addictionSignal: 'Refuses simple tasks as regression',
      allergySignal: 'Cannot engage even at simple level',
    },
  },
};
