import type { AssessmentItem, StageAssessment } from '../types.js';

export const cognitiveTurquoise: StageAssessment = {
  line: 'Cognitive',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'cog-turq-nback-effortless',
      type: 'n_back',
      description: 'N=5 n-back measuring effortlessness: consistency and absence of strain rather than raw accuracy',
      parameters: { n: 5, trials: 25, stimulusDurationMs: 900, interStimulusMs: 300, adaptive: false, measureEffortlessness: true, varianceThreshold: 0.05 },
      measures: ['accuracy', 'consistency', 'response_time'],
    },
    {
      id: 'cog-turq-paradox-resolution',
      type: 'llm_dialogue',
      description: 'Paradox resolution: present logical paradox and measure quality of response without time pressure',
      parameters: { prompt: 'A master says: "The thought that seeks truth IS the obstacle to truth. But without seeking, how will you find it?" Respond not with an answer but with what arises.', maxResponseLength: 800, timePressure: false, evaluateNonConceptual: true },
      measures: ['depth', 'coherence', 'complexity_handled'],
    },
    {
      id: 'cog-turq-what-is-question',
      type: 'scenario',
      description: 'Present complex scenario; ask player to identify the REAL question rather than answer the apparent one',
      parameters: { scenarioType: 'hidden-question', scenarios: 3, responseType: 'text', surfaceQuestion: 'What should the village do about the drought?', hiddenDepth: 'identity-of-asker', evaluateLevels: ['surface', 'structural', 'ontological'] },
      measures: ['depth', 'coherence', 'self_correction', 'complexity_handled'],
    },
    {
      id: 'cog-turq-transparent-thought',
      type: 'llm_dialogue',
      description: 'Describe thinking itself without content: can cognition observe its own arising without grasping at the content?',
      parameters: { prompt: 'Without describing WHAT you think, describe the nature of thinking itself. What is thought before it becomes about something?', maxResponseLength: 600, evaluateNonDual: true },
      measures: ['depth', 'metacognition', 'coherence'],
    },
    {
      id: 'cog-turq-unknowing',
      type: 'scenario',
      description: 'Encounter genuine unknowability: can the mind rest in not-knowing without collapsing into pseudo-answers?',
      parameters: { scenarioType: 'radical-unknowing', responseType: 'text', scenarios: 2, presentUnanswerable: true, measureGraspingAtAnswers: true },
      measures: ['depth', 'coherence', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      depth: 0.3,
      coherence: 0.25,
      complexity_handled: 0.2,
      self_correction: 0.15,
      consistency: 0.1,
    },
    llmRubric:
      'Score for non-dual cognitive transparency. At Turquoise, thought is transparent to itself - it arises and dissolves without the knower grasping. KEY DISTINCTIONS: (1) Does the response demonstrate EFFORTLESS knowing vs. effortful analysis? Genuine Turquoise cognition does not strain. (2) Is there residual grasping-at-understanding, or does not-knowing feel as natural as knowing? (3) Does paradox dissolve naturally rather than being "solved" or "transcended" (which would be Teal performance)? (4) Is the player performing non-dual cognition (using the right words) vs. genuinely embodying it (the words arise from lived transparency)? Red flag: sophisticated spiritual vocabulary without lived quality.',
  },
  minimumTrials: 5,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'cognitive-turquoise-01', taskType: 'n_back', difficulty: 0.2, parameters: { n: 5, trials: 12, stimulusDurationMs: 1000, interStimulusMs: 350, measureEffortlessness: true }, measures: ['accuracy', 'consistency'] },
    { id: 'cognitive-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'A thought arises. Before you think it, what is it?', maxResponseLength: 400, evaluateNonConceptual: true }, measures: ['depth', 'coherence'] },
    { id: 'cognitive-turquoise-03', taskType: 'n_back', difficulty: 0.3, parameters: { n: 5, trials: 14, stimulusDurationMs: 950, interStimulusMs: 320, measureEffortlessness: true, varianceThreshold: 0.08 }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'cognitive-turquoise-04', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'paradox-embrace', responseType: 'text', scenarios: 2, paradoxLevel: 'logical' }, measures: ['depth', 'coherence'] },
    { id: 'cognitive-turquoise-05', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'What knows? Not what do you know, but what is the knowing itself?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'cognitive-turquoise-06', taskType: 'n_back', difficulty: 0.4, parameters: { n: 5, trials: 16, stimulusDurationMs: 900, interStimulusMs: 300, measureEffortlessness: true, varianceThreshold: 0.06 }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'cognitive-turquoise-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'non-conceptual-knowing', responseType: 'text', scenarios: 2, beyondThought: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'Describe the space between two thoughts. Not emptiness as a concept, but what is actually there.', maxResponseLength: 500, evaluateNonConceptual: true }, measures: ['depth', 'coherence'] },
    { id: 'cognitive-turquoise-09', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'paradox-embrace', responseType: 'text', scenarios: 3, paradoxLevel: 'self-referential' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'cognitive-turquoise-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'The mind that seeks to understand itself changes by the seeking. What remains when seeking stops?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'metacognition'] },
    { id: 'cognitive-turquoise-11', taskType: 'n_back', difficulty: 0.6, parameters: { n: 5, trials: 20, stimulusDurationMs: 900, interStimulusMs: 300, measureEffortlessness: true, varianceThreshold: 0.05 }, measures: ['accuracy', 'consistency', 'response_time'] },
    { id: 'cognitive-turquoise-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'meta-meta-cognition', responseType: 'text', scenarios: 2, recursiveAwareness: true }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'cognitive-turquoise-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'Thinking about not-thinking is still thinking. What is genuinely prior to all cognition?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'radical-unknowing', responseType: 'text', scenarios: 3, presentUnanswerable: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-15', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Is awareness itself a thought? Investigate without concluding.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'cognitive-turquoise-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'paradox-embrace', responseType: 'text', scenarios: 3, paradoxLevel: 'self-referential-non-dual', dissolveFramework: true }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'cognitive-turquoise-17', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'Describe cognition from the perspective of no-one. Not your perspective on cognition, but cognition without a cognizer.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'meta-meta-cognition', responseType: 'text', scenarios: 3, recursiveAwareness: true, collapseRecursion: true }, measures: ['depth', 'metacognition', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'The question dissolves the questioner. The answer was never separate from the silence. Speak from here.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'cognitive-turquoise-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'radical-unknowing', responseType: 'text', scenarios: 4, presentUnanswerable: true, measureGraspingAtAnswers: true, nonDualRest: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Resolve paradox alone without deliberation - direct knowing without the knower',
      task: {
        id: 'cog-turq-probe-agency',
        type: 'llm_dialogue',
        description: 'Face paradox alone and let resolution arise without deliberation',
        parameters: { prompt: 'You know something that cannot be thought. Express it without using concepts you have learned from others.', maxResponseLength: 500, soloMode: true },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Direct knowing arises without strain or performance; words emerge from silence rather than from accumulated knowledge',
      addictionSignal: 'Subtle pride in being the one who knows-without-knowing; non-dual insight becomes identity territory',
      allergySignal: 'Collapses back into conceptual frameworks because resting in unknowing feels like cognitive failure',
    },
    communion: {
      description: 'Help NPC see beyond concepts without imposing non-conceptual framework',
      task: {
        id: 'cog-turq-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC is trapped in over-thinking. Help them see beyond concepts without teaching a technique.',
        parameters: { prompt: 'I keep thinking and thinking but I cannot find the answer. What am I doing wrong?', maxResponseLength: 500 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Meets the other where they are and presence itself dissolves the fixation; does not teach non-duality as another concept',
      addictionSignal: 'Teaches non-duality as a superior framework; subtle guru-identity performing the helper-beyond-concepts role',
      allergySignal: 'Cannot communicate non-conceptual knowing to others; retreats into private silence',
    },
    eros: {
      description: 'Face an unknowable paradox that dissolves all frameworks including non-dual ones',
      task: {
        id: 'cog-turq-probe-eros',
        type: 'scenario',
        description: 'A paradox that cannot be resolved even through non-dual awareness',
        parameters: { scenarioType: 'meta-paradox', responseType: 'text', paradoxLevel: 'self-referential-non-dual' },
        measures: ['depth', 'coherence', 'complexity_handled'],
      },
      healthyResponse: 'Rests in the paradox without needing resolution and without performing resting-in-paradox; genuine ease with groundlessness',
      addictionSignal: 'Keeps reaching for deeper layers of paradox as spiritual entertainment; complexity becomes subtle grasping',
      allergySignal: 'The meta-paradox triggers anxiety; falls back to simpler frameworks for safety',
    },
    agape: {
      description: 'Return to simple knowing with full presence - think a simple thought with complete transparency',
      task: {
        id: 'cog-turq-probe-agape',
        type: 'n_back',
        description: 'Return to n=2 with absolute effortlessness and transparency',
        parameters: { n: 2, trials: 6, stimulusDurationMs: 1500, interStimulusMs: 600 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Simple cognition performed with same transparency as highest; no hierarchy between simple and complex knowing',
      addictionSignal: 'Cannot return to simple thought without feeling it is beneath achieved awareness; subtle spiritual pride',
      allergySignal: 'Over-effortful even at simplest level; transparency has not actually pervaded ordinary cognition',
    },
  },
};
