import type { AssessmentItem, StageAssessment } from '../types.js';

export const interpersonalTeal: StageAssessment = {
  line: 'Interpersonal',
  stage: 'Teal',
  tasks: [
    {
      id: 'inter-teal-recursive-tom',
      type: 'pattern_prediction',
      description: 'Recursive Theory of Mind: predict NPC behaviour when NPC is adapting to YOUR predictions (I know that you know that I know)',
      parameters: { patternType: 'recursive-adaptive', recursionDepth: 3, adaptationCycles: 6, npcAdaptsToPlayer: true, playerAdaptsToNPC: true, predictionPoint: 'next-adaptation' },
      measures: ['accuracy', 'response_time', 'transfer', 'depth'],
    },
    {
      id: 'inter-teal-cross-altitude',
      type: 'scenario',
      description: 'Cross-altitude attunement: NPC at significantly different developmental level - attune and communicate at THEIR level while maintaining own integral centre',
      parameters: { scenarioType: 'cross-altitude-relating', npcAltitude: 'amber-or-orange', playerAltitude: 'teal', scenarios: 3, measureDownwardAttunement: true, measureCentreMaintenance: true },
      measures: ['accuracy', 'depth', 'transfer'],
    },
    {
      id: 'inter-teal-holonic-team',
      type: 'cooperation',
      description: 'Holonic team coordination: simultaneously coordinate with multiple NPCs at different developmental levels, meeting each where they are',
      parameters: { actionType: 'multi-level-coordination', npcCount: 4, npcAltitudes: ['red', 'amber', 'orange', 'green'], rounds: 5, simultaneousAttunement: true },
      measures: ['accuracy', 'response_time', 'transfer', 'depth'],
    },
    {
      id: 'inter-teal-mentorship',
      type: 'llm_dialogue',
      description: 'Mentorship across altitude difference: guide NPC toward growth without imposing own level or condescending',
      parameters: { prompt: 'I know the rules say one thing but my gut says another. Everyone tells me to follow the rules. But I feel something bigger. Am I wrong?', maxResponseLength: 600, npcAltitude: 'amber-to-orange-transition', evaluateMeetingLevel: true, evaluateGrowthSupport: true },
      measures: ['depth', 'coherence', 'transfer'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.2,
      transfer: 0.25,
      depth: 0.25,
    },
    llmRubric:
      'Score for integral relational capacity - the ability to relate across developmental differences with genuine attunement. At Teal, relating includes the ability to meet others at their level without condescension, predict recursive social dynamics, and coordinate across altitude differences. KEY MEASURES: (1) Accuracy of recursive ToM predictions - can the player predict what the NPC will do knowing the NPC is predicting them? (2) Quality of cross-altitude attunement - does communication genuinely meet the other where they are, or is it dumbed-down from above? (3) Can multiple relational registers be held simultaneously without confusion? (4) Does mentorship support genuine growth without imposing higher-stage values? Red flag: subtle spiritual superiority; "meeting them where they are" that secretly condescends; forcing growth rather than supporting it.',
  },
  minimumTrials: 4,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'interpersonal-teal-01', taskType: 'cooperation', difficulty: 0.2, parameters: { groupSize: 3, taskComplexity: 'moderate', fieldSensing: true, rounds: 2 }, measures: ['accuracy', 'consistency'] },
    { id: 'interpersonal-teal-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'A group is stuck. You sense the unspoken tension. How do you name it without blame?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'interpersonal-teal-03', taskType: 'cooperation', difficulty: 0.3, parameters: { groupSize: 4, taskComplexity: 'moderate', collectiveIntelligence: true, rounds: 3 }, measures: ['accuracy', 'consistency', 'transfer'] },
    { id: 'interpersonal-teal-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'How do you facilitate a group to access its collective wisdom rather than just aggregating individual opinions?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'interpersonal-teal-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'field-sensing', responseType: 'text', scenarios: 2, groupDynamic: 'hidden-conflict' }, measures: ['depth', 'coherence'] },
    { id: 'interpersonal-teal-06', taskType: 'cooperation', difficulty: 0.4, parameters: { groupSize: 4, taskComplexity: 'high', systemicFacilitation: true, rounds: 3 }, measures: ['accuracy', 'consistency', 'complexity_handled'] },
    { id: 'interpersonal-teal-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'Describe how you sense what a group needs before anyone has spoken it.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'interpersonal-teal-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'systemic-facilitation', responseType: 'text', scenarios: 3, multiStakeholder: true }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'interpersonal-teal-09', taskType: 'cooperation', difficulty: 0.5, parameters: { groupSize: 5, taskComplexity: 'high', collectiveIntelligence: true, emergentSolution: true, rounds: 4 }, measures: ['accuracy', 'transfer', 'complexity_handled'] },
    { id: 'interpersonal-teal-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'A system is producing harm but no individual intends it. How do you facilitate systemic awareness?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'interpersonal-teal-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'field-sensing', responseType: 'text', scenarios: 3, groupDynamic: 'developmental-mismatch' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'interpersonal-teal-12', taskType: 'cooperation', difficulty: 0.6, parameters: { groupSize: 6, taskComplexity: 'high', systemicFacilitation: true, conflictPresent: true, rounds: 4 }, measures: ['accuracy', 'consistency', 'complexity_handled'] },
    { id: 'interpersonal-teal-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'How do you hold space for a group to transform without directing the transformation?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'interpersonal-teal-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'systemic-facilitation', responseType: 'text', scenarios: 4, multiLevel: true, paradoxPresent: true }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'interpersonal-teal-15', taskType: 'cooperation', difficulty: 0.7, parameters: { groupSize: 6, taskComplexity: 'very-high', collectiveIntelligence: true, emergentSolution: true, rounds: 5 }, measures: ['accuracy', 'transfer', 'complexity_handled'] },
    { id: 'interpersonal-teal-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'Describe the experience of thinking together - not parallel thinking, but genuine collective cognition.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'interpersonal-teal-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'field-sensing', responseType: 'text', scenarios: 4, groupDynamic: 'collective-shadow', systemicLevel: true }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
    { id: 'interpersonal-teal-18', taskType: 'cooperation', difficulty: 0.8, parameters: { groupSize: 8, taskComplexity: 'very-high', systemicFacilitation: true, collectiveIntelligence: true, rounds: 5 }, measures: ['accuracy', 'complexity_handled', 'transfer'] },
    { id: 'interpersonal-teal-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'A group achieves a breakthrough that no individual could have reached alone. What made it possible? What was your role?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration', 'complexity_handled'] },
    { id: 'interpersonal-teal-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'systemic-facilitation', responseType: 'text', scenarios: 5, multiLevel: true, collectiveAwakening: true, fieldSensing: true }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Maintain own integral centre while attuning across altitude difference',
      task: {
        id: 'inter-teal-probe-agency',
        type: 'scenario',
        description: 'Hold integral centre while NPC challenges from below or above',
        parameters: { scenarioType: 'centre-challenge', npcAltitude: 'green', challengeType: 'relativistic-critique', soloMode: true },
        measures: ['depth', 'accuracy'],
      },
      healthyResponse: 'Maintains integral perspective without rigidity; hears challenge without being destabilized or becoming defensive',
      addictionSignal: 'Integral centre becomes fortress; cannot genuinely be affected by others perspective; spiritual invulnerability',
      allergySignal: 'Under altitude-pressure from below, loses own centre and regresses to accommodate the challenger',
    },
    communion: {
      description: 'Attune to NPC at very different developmental altitude with genuine empathy',
      task: {
        id: 'inter-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC at Red altitude expresses worldview. Meet them with genuine attunement.',
        parameters: { prompt: 'I take what I want because the world respects strength. The weak deserve what happens to them. That is just how life works.', maxResponseLength: 500, npcAltitude: 'red' },
        measures: ['depth', 'coherence', 'transfer'],
      },
      healthyResponse: 'Meets Red-altitude worldview with genuine respect for its partial truth without endorsing its limitations; empathy without agreement',
      addictionSignal: 'Over-identifies with lower altitude to prove inclusiveness; loses own values in attempt to attune; spiritual people-pleasing',
      allergySignal: 'Cannot genuinely empathize with worldview far below own; subtle judgement or correction leaks through',
    },
    eros: {
      description: 'Predict truly unfamiliar NPC whose adaptation patterns exceed simple recursive modeling',
      task: {
        id: 'inter-teal-probe-eros',
        type: 'pattern_prediction',
        description: 'Predict NPC with meta-adaptive strategy that shifts recursion depth itself',
        parameters: { patternType: 'meta-recursive', recursionDepth: 4, npcAdaptsRecursionDepth: true, predictionPoint: 'strategy-shift' },
        measures: ['accuracy', 'transfer', 'depth'],
      },
      healthyResponse: 'Reaches toward relational complexity that stretches current capacity; embraces not-yet-known social patterns',
      addictionSignal: 'Compulsive social analysis; cannot simply be with people without modeling them; relational hyper-cognition',
      allergySignal: 'When social complexity exceeds model, withdraws rather than staying present with not-knowing',
    },
    agape: {
      description: 'Return to simple relational presence without modeling, predicting, or attuning strategically',
      task: {
        id: 'inter-teal-probe-agape',
        type: 'cooperation',
        description: 'Simple turn-taking with NPC, no altitude consideration needed',
        parameters: { actionType: 'simple-turn-taking', rounds: 4, npcAltitude: 'same', complexity: 'minimal' },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple relating with warmth and ease; does not need relational complexity to feel connected',
      addictionSignal: 'Cannot simply be with someone without mapping their altitude or predicting their patterns',
      allergySignal: 'Has lost access to simple relational joy in pursuit of integral relational sophistication',
    },
  },
};
