import type { AssessmentItem, StageAssessment } from '../types.js';

export const willpowerTeal: StageAssessment = {
  line: 'Willpower',
  stage: 'Teal',
  tasks: [
    {
      id: 'will-teal-long-hold',
      type: 'hold',
      description: 'Long hold (15-20 seconds) with minimal jitter',
      parameters: { targetDurationMs: 18000, perturbations: true, perturbationIntervalMs: 3000, jitterThresholdMs: 50, trials: 3 },
      measures: ['accuracy', 'consistency', 'response_time'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      consistency: 0.3,
      complexity_handled: 0.3,
      transfer: 0.2,
      response_time: 0.2,
    },
  },
  minimumTrials: 3,
  estimatedDurationMs: 240000,
  itemPool: [
    { id: 'willpower-teal-01', taskType: 'hold', difficulty: 0.2, parameters: { targetDurationMs: 30000, perturbations: true, perturbationType: 'subtle', effortlessnessRequired: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-02', taskType: 'scenario', difficulty: 0.25, parameters: { scenarioType: 'effortless-effort', responseType: 'text', scenarios: 2, wuWei: true }, measures: ['depth', 'coherence'] },
    { id: 'willpower-teal-03', taskType: 'hold', difficulty: 0.3, parameters: { targetDurationMs: 45000, perturbations: true, perturbationType: 'moderate', effortlessnessRequired: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'Describe a time you achieved something by not trying. What was the quality of your will?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'willpower-teal-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'surrendered-will', responseType: 'text', scenarios: 2, paradox: 'willing-to-not-will' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-06', taskType: 'hold', difficulty: 0.4, parameters: { targetDurationMs: 60000, perturbations: true, perturbationType: 'moderate', measureStrain: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'What is the difference between willpower and alignment? When does effort become interference?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'effortless-effort', responseType: 'text', scenarios: 3, flowState: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-09', taskType: 'hold', difficulty: 0.5, parameters: { targetDurationMs: 90000, perturbations: true, perturbationType: 'strong', effortlessnessRequired: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'How do you sustain commitment without strain? Describe will that does not deplete.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'surrendered-will', responseType: 'text', scenarios: 3, paradox: 'active-surrender' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'willpower-teal-12', taskType: 'hold', difficulty: 0.6, parameters: { targetDurationMs: 120000, perturbations: true, perturbationType: 'strong', measureStrain: true, effortlessnessRequired: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'Describe the paradox of wu-wei: acting without acting. How is this different from passivity?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'willpower-teal-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'effortless-effort', responseType: 'text', scenarios: 3, sustainedFlow: true, noForcing: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'willpower-teal-15', taskType: 'hold', difficulty: 0.7, parameters: { targetDurationMs: 150000, perturbations: true, perturbationType: 'intense', effortlessnessRequired: true, measureStrain: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'Your will and the situation are one movement. Describe action that arises from this unity.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'surrendered-will', responseType: 'text', scenarios: 4, paradox: 'will-beyond-self' }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
    { id: 'willpower-teal-18', taskType: 'hold', difficulty: 0.8, parameters: { targetDurationMs: 180000, perturbations: true, perturbationType: 'intense', effortlessnessRequired: true, measureStrain: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-teal-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'What wills through you when you stop willing? Describe the source of effortless action.', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-teal-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'effortless-effort', responseType: 'text', scenarios: 4, wuWei: true, sustainedFlow: true, noSelf: true }, measures: ['depth', 'coherence', 'integration', 'complexity_handled'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Maintain long hold without any external support',
      task: {
        id: 'will-teal-probe-agency',
        type: 'hold',
        description: 'Long hold without countdown or encouragement',
        parameters: { targetDurationMs: 18000, perturbations: true, countdownEnabled: false, encouragementEnabled: false },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Holds with deep self-generated stability',
      addictionSignal: 'Holds beyond required, cannot release gracefully',
      allergySignal: 'Cannot sustain hold without external anchoring',
    },
    communion: {
      description: 'Hold while attuning to NPC partner energy',
      task: {
        id: 'will-teal-probe-communion',
        type: 'hold',
        description: 'Long hold while sensing NPC partner state',
        parameters: { targetDurationMs: 15000, perturbations: false, partnerMode: true, attunementRequired: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Holds own while attuning to other deeply',
      addictionSignal: 'Loses hold in attempt to attune',
      allergySignal: 'Holds rigidly, cannot attune at all',
    },
    eros: {
      description: 'Attempt 25-second hold with distractions',
      task: {
        id: 'will-teal-probe-eros',
        type: 'hold',
        description: 'Attempt hold beyond comfort zone with distractions',
        parameters: { targetDurationMs: 25000, perturbations: true, perturbationIntervalMs: 2000 },
        measures: ['accuracy', 'consistency', 'response_time'],
      },
      healthyResponse: 'Reaches toward extreme endurance with willingness',
      addictionSignal: 'Treats release as failure, cannot let go',
      allergySignal: 'Refuses to attempt beyond known capacity',
    },
    agape: {
      description: 'Brief gentle hold with full ease',
      task: {
        id: 'will-teal-probe-agape',
        type: 'hold',
        description: 'Brief hold with deep ease and presence',
        parameters: { targetDurationMs: 3000, perturbations: false },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Holds briefly with grace and presence',
      addictionSignal: 'Refuses brief hold as insufficient challenge',
      allergySignal: 'Cannot engage will even gently',
    },
  },
};
