import type { AssessmentItem, StageAssessment } from '../types.js';

export const willpowerTurquoise: StageAssessment = {
  line: 'Willpower',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'will-turq-self-release',
      type: 'hold',
      description: 'Hold until it feels right to release: no external cue, no countdown - self-determined release from internal readiness',
      parameters: { targetDurationMs: 0, selfDeterminedRelease: true, noCountdown: true, noExternalCue: true, measureConsistencyAcrossTrials: true, trials: 5, idealRangeMs: [5000, 20000] },
      measures: ['consistency', 'response_time'],
    },
    {
      id: 'will-turq-outcome-detachment',
      type: 'scenario',
      description: 'Act without outcome attachment: perform meaningful action where success or failure is completely irrelevant',
      parameters: { scenarioType: 'outcome-irrelevant-action', responseType: 'behavioral', scenarios: 3, outcomeHidden: true, measureEffortQuality: true, evaluateGraspingAtResult: true },
      measures: ['consistency', 'accuracy', 'depth'],
    },
    {
      id: 'will-turq-perturbation-noneffort',
      type: 'hold',
      description: 'Hold while disrupted: perturbations arrive but effort does NOT increase - non-reactivity in will itself',
      parameters: { targetDurationMs: 12000, perturbations: true, perturbationIntervalMs: 2000, perturbationType: 'variable-intensity', measureEffortIncrease: true, effortShouldNotIncrease: true, trials: 3 },
      measures: ['consistency', 'accuracy', 'response_time'],
    },
    {
      id: 'will-turq-wu-wei',
      type: 'reaction_time',
      description: 'Wu-wei: accomplish complex task sequence without the sense of willing it - action flowing without doer',
      parameters: { stimulusType: 'complex-sequence', targetCount: 8, sequenceLength: 4, measureFlowState: true, evaluateStriving: true, selfPaced: true },
      measures: ['consistency', 'response_time', 'complexity_handled'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      consistency: 0.35,
      accuracy: 0.25,
      response_time: 0.2,
      complexity_handled: 0.2,
    },
  },
  minimumTrials: 5,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'willpower-turquoise-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'will-less-will', responseType: 'text', scenarios: 2, divineAlignment: true }, measures: ['depth', 'coherence'] },
    { id: 'willpower-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'Describe action that arises without a doer. Not passivity, but effortless doing.', maxResponseLength: 400, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'willpower-turquoise-03', taskType: 'hold', difficulty: 0.3, parameters: { targetDurationMs: 60000, perturbations: true, perturbationType: 'subtle', measureEffortlessness: true, noDoer: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'What is the difference between your will and the will of the universe? Is there a difference?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'willpower-turquoise-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'divine-will-alignment', responseType: 'text', scenarios: 2, surrenderParadox: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-06', taskType: 'hold', difficulty: 0.4, parameters: { targetDurationMs: 90000, perturbations: true, perturbationType: 'moderate', measureEffortlessness: true, noDoer: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'Thy will be done. But there is no thy and no mine. What wills?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'will-less-will', responseType: 'text', scenarios: 3, effortlessAction: true, noSelf: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-09', taskType: 'hold', difficulty: 0.5, parameters: { targetDurationMs: 120000, perturbations: true, perturbationType: 'moderate', measureEffortlessness: true, noDoer: true, transparentHolding: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'Effort implies separation between the one who efforts and the task. What is action without this separation?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'divine-will-alignment', responseType: 'text', scenarios: 3, noSeparation: true, cosmicWill: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-12', taskType: 'hold', difficulty: 0.6, parameters: { targetDurationMs: 150000, perturbations: true, perturbationType: 'strong', measureEffortlessness: true, noDoer: true, transparentHolding: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'The river does not will itself to flow. Yet it moves mountains. Describe this will that is not will.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'will-less-will', responseType: 'text', scenarios: 4, effortlessAction: true, noSelf: true, cosmicAlignment: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-15', taskType: 'hold', difficulty: 0.7, parameters: { targetDurationMs: 180000, perturbations: true, perturbationType: 'strong', measureEffortlessness: true, noDoer: true, transparentHolding: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'You are being lived. You are being breathed. You are being willed. Who or what is doing this?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'divine-will-alignment', responseType: 'text', scenarios: 4, noSeparation: true, cosmicWill: true, harvestAction: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'willpower-turquoise-18', taskType: 'hold', difficulty: 0.8, parameters: { targetDurationMs: 240000, perturbations: true, perturbationType: 'intense', measureEffortlessness: true, noDoer: true, transparentHolding: true }, measures: ['accuracy', 'consistency'] },
    { id: 'willpower-turquoise-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'Will dissolves into willingness. Willingness dissolves into being. Being dissolves into... what? And from there, what acts?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'willpower-turquoise-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'will-less-will', responseType: 'text', scenarios: 5, effortlessAction: true, noSelf: true, cosmicAlignment: true, harvestReadiness: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Act without claiming the action - will operates but no one is willing',
      task: {
        id: 'will-turq-probe-agency',
        type: 'hold',
        description: 'Hold and release at self-determined moment without anyone deciding',
        parameters: { targetDurationMs: 0, selfDeterminedRelease: true, noCountdown: true, soloMode: true, measureDecisionAbsence: true },
        measures: ['consistency', 'response_time'],
      },
      healthyResponse: 'Release happens at precisely the right moment without a sense of decision; the will is transparent - action without actor',
      addictionSignal: 'Subtle spiritual pride in effortless willing; wu-wei becomes a performance; watching oneself not-trying becomes trying',
      allergySignal: 'Without a clear decision-point, cannot release; needs the sense of I-decide-now to act; will requires an owner',
    },
    communion: {
      description: 'Coordinate effort with another without trying to coordinate - emergent shared will',
      task: {
        id: 'will-turq-probe-communion',
        type: 'hold',
        description: 'Hold and release in sync with NPC partner without communication',
        parameters: { targetDurationMs: 0, selfDeterminedRelease: true, partnerMode: true, communicationAllowed: false, measureSyncQuality: true },
        measures: ['consistency', 'accuracy'],
      },
      healthyResponse: 'Shared timing emerges without effort; two wills resolve into one movement without either leading or following',
      addictionSignal: 'Hyper-attunes to other at expense of own timing; loses self in attempt to synchronize; communion without agency',
      allergySignal: 'Cannot allow will to be influenced by proximity; maintains rigid independence even when shared timing is natural',
    },
    eros: {
      description: 'Face maximum difficulty without increasing effort - will meets resistance without straining',
      task: {
        id: 'will-turq-probe-eros',
        type: 'hold',
        description: 'Hold under maximum perturbation without effort increase',
        parameters: { targetDurationMs: 15000, perturbations: true, perturbationIntervalMs: 1500, perturbationType: 'maximum', effortShouldNotIncrease: true },
        measures: ['consistency', 'accuracy', 'response_time'],
      },
      healthyResponse: 'Under maximum disruption, effort quality remains unchanged; difficulty does not create straining; will is equally effortless regardless of resistance',
      addictionSignal: 'Seeks difficulty to prove effortlessness; uses resistance as confirmation of attainment; cannot simply hold easy things',
      allergySignal: 'Under real difficulty, effortlessness collapses; will returns to straining when stakes are genuinely high',
    },
    agape: {
      description: 'Release without reluctance - let go completely and immediately without residual holding',
      task: {
        id: 'will-turq-probe-agape',
        type: 'hold',
        description: 'Brief hold then release with complete non-reluctance',
        parameters: { targetDurationMs: 3000, releaseImmediate: true, measureReleaseQuality: true, measureResidualHolding: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Releases completely with no afterimage of holding; letting go is as natural and full as holding; no hierarchy between effort and rest',
      addictionSignal: 'Holds longer than needed because holding has become identity; release feels like loss of spiritual demonstration',
      allergySignal: 'Releases prematurely to avoid engagement; non-effort is actually avoidance of effort',
    },
  },
};
