import type { AssessmentItem, StageAssessment } from '../types.js';

export const somaticTeal: StageAssessment = {
  line: 'Somatic',
  stage: 'Teal',
  tasks: [
    {
      id: 'som-teal-anticipatory',
      type: 'reaction_time',
      description: 'Anticipatory timing: respond just before stimulus (predict timing)',
      parameters: { stimulusType: 'predictable-pattern', targetCount: 12, anticipationWindowMs: 100 },
      measures: ['accuracy', 'response_time', 'consistency'],
    },
    {
      id: 'som-teal-interoceptive',
      type: 'scenario',
      description: 'Interoceptive precision: describe internal somatic state',
      parameters: { scenarioType: 'interoceptive-report', responseType: 'text', scenarios: 4 },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      accuracy: 0.3,
      response_time: 0.3,
      consistency: 0.4,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 210000,
  itemPool: [
    { id: 'somatic-teal-01', taskType: 'rhythm', difficulty: 0.2, parameters: { beatsPerMinute: 60, beats: 8, tolerance: 0.15, subtleBody: true }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-teal-02', taskType: 'self_report', difficulty: 0.25, parameters: { prompts: ['Describe the energy you feel in your hands right now.'], responseType: 'text', somaticAwareness: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-teal-03', taskType: 'rhythm', difficulty: 0.3, parameters: { beatsPerMinute: 72, beats: 12, tolerance: 0.12, subtleBody: true, energySensing: true }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-teal-04', taskType: 'self_report', difficulty: 0.35, parameters: { prompts: ['Where in your body do you sense the boundary between inside and outside?'], responseType: 'text', somaticAwareness: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-teal-05', taskType: 'rhythm', difficulty: 0.4, parameters: { beatsPerMinute: 80, beats: 16, tolerance: 0.1, subtleBody: true, multiLayer: true }, measures: ['accuracy', 'consistency', 'complexity_handled'] },
    { id: 'somatic-teal-06', taskType: 'self_report', difficulty: 0.4, parameters: { prompts: ['Describe the felt-sense of your spine as a channel of energy.'], responseType: 'text', energySensing: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-teal-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'somatic-integration', responseType: 'text', scenarios: 2, bodyMindUnity: true }, measures: ['depth', 'integration'] },
    { id: 'somatic-teal-08', taskType: 'rhythm', difficulty: 0.5, parameters: { beatsPerMinute: 90, beats: 16, tolerance: 0.08, subtleBody: true, breathSync: true }, measures: ['accuracy', 'consistency', 'integration'] },
    { id: 'somatic-teal-09', taskType: 'self_report', difficulty: 0.5, parameters: { prompts: ['Sense the space around your body. Where does your energy field end?'], responseType: 'text', energySensing: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-teal-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'somatic-integration', responseType: 'text', scenarios: 3, emotionInBody: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'somatic-teal-11', taskType: 'rhythm', difficulty: 0.55, parameters: { beatsPerMinute: 100, beats: 20, tolerance: 0.08, subtleBody: true, polyrhythm: true }, measures: ['accuracy', 'consistency', 'complexity_handled'] },
    { id: 'somatic-teal-12', taskType: 'self_report', difficulty: 0.6, parameters: { prompts: ['Describe the sensation of awareness moving through your body.'], responseType: 'text', subtleBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-teal-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'somatic-integration', responseType: 'text', scenarios: 3, energyCircuit: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'somatic-teal-14', taskType: 'rhythm', difficulty: 0.65, parameters: { beatsPerMinute: 108, beats: 24, tolerance: 0.06, subtleBody: true, breathSync: true, energyFlow: true }, measures: ['accuracy', 'consistency', 'integration'] },
    { id: 'somatic-teal-15', taskType: 'self_report', difficulty: 0.7, parameters: { prompts: ['Feel into the cellular level. What do your cells know that your mind does not?'], responseType: 'text', cellularAwareness: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-teal-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'somatic-integration', responseType: 'text', scenarios: 4, fullBodyIntegration: true }, measures: ['depth', 'integration', 'coherence', 'complexity_handled'] },
    { id: 'somatic-teal-17', taskType: 'rhythm', difficulty: 0.8, parameters: { beatsPerMinute: 120, beats: 24, tolerance: 0.05, subtleBody: true, multiLayer: true, energyFlow: true }, measures: ['accuracy', 'consistency', 'complexity_handled'] },
    { id: 'somatic-teal-18', taskType: 'self_report', difficulty: 0.8, parameters: { prompts: ['Describe the body as a field of intelligence rather than a collection of parts.'], responseType: 'text', fieldAwareness: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-teal-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'somatic-integration', responseType: 'text', scenarios: 4, subtleBody: true, energyCircuit: true, fieldSensing: true }, measures: ['depth', 'integration', 'coherence', 'complexity_handled'] },
    { id: 'somatic-teal-20', taskType: 'rhythm', difficulty: 0.9, parameters: { beatsPerMinute: 120, beats: 32, tolerance: 0.04, subtleBody: true, polyrhythm: true, breathSync: true, energyFlow: true }, measures: ['accuracy', 'consistency', 'complexity_handled', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Anticipate timing without external cues',
      task: {
        id: 'som-teal-probe-agency',
        type: 'reaction_time',
        description: 'Anticipate timing from internal sense only',
        parameters: { stimulusType: 'predictable-pattern', targetCount: 8, anticipationWindowMs: 100, cuesEnabled: false },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Anticipates from internal somatic knowing',
      addictionSignal: 'Over-controls timing, mechanical precision',
      allergySignal: 'Cannot anticipate without external cues',
    },
    communion: {
      description: 'Synchronize anticipatory timing with NPC',
      task: {
        id: 'som-teal-probe-communion',
        type: 'reaction_time',
        description: 'Synchronize anticipatory timing with NPC partner',
        parameters: { stimulusType: 'predictable-pattern', targetCount: 8, partnerMode: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Syncs anticipation with other while holding own',
      addictionSignal: 'Loses own timing to sync perfectly',
      allergySignal: 'Cannot sync somatic timing with another',
    },
    eros: {
      description: 'Attempt anticipation with irregular pattern',
      task: {
        id: 'som-teal-probe-eros',
        type: 'reaction_time',
        description: 'Anticipate timing in subtly irregular pattern',
        parameters: { stimulusType: 'slightly-irregular', targetCount: 10, anticipationWindowMs: 75 },
        measures: ['accuracy', 'response_time'],
      },
      healthyResponse: 'Reaches toward subtle pattern detection',
      addictionSignal: 'Forces pattern onto randomness',
      allergySignal: 'Refuses engagement with irregular pattern',
    },
    agape: {
      description: 'Return to simple reaction with somatic ease',
      task: {
        id: 'som-teal-probe-agape',
        type: 'reaction_time',
        description: 'Simple reaction with full somatic ease',
        parameters: { stimulusType: 'simple', targetCount: 6, minGap: 1500, maxGap: 3000 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple body response with ease',
      addictionSignal: 'Refuses simple somatic engagement',
      allergySignal: 'Cannot engage body at any level',
    },
  },
};
