import type { AssessmentItem, StageAssessment } from '../types.js';

export const somaticTurquoise: StageAssessment = {
  line: 'Somatic',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'som-turq-self-timing',
      type: 'reaction_time',
      description: 'Respond when it feels right: no external cue, self-determined timing from internal readiness',
      parameters: { stimulusType: 'none', targetCount: 10, selfDetermined: true, measureConsistencyOfInternal: true, minGap: 2000, maxGap: 8000, noExternalCue: true },
      measures: ['consistency', 'response_time'],
    },
    {
      id: 'som-turq-effortless-complex',
      type: 'rhythm',
      description: 'Effortless complex action: perform complex rhythm pattern measuring absence of strain via variance analysis',
      parameters: { pattern: [1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1], bpm: 90, trials: 4, measureEffort: true, varianceAsKey: true, strainDetection: true },
      measures: ['consistency', 'accuracy', 'response_time'],
    },
    {
      id: 'som-turq-stillness-in-motion',
      type: 'hold',
      description: 'Stillness-in-motion: maintain inner steadiness while responding to changing external stimuli',
      parameters: { targetDurationMs: 15000, movingTarget: true, responseRequired: true, measureInternalStability: true, externalChangeRate: 'variable' },
      measures: ['consistency', 'accuracy', 'response_time'],
    },
    {
      id: 'som-turq-naturalness',
      type: 'reaction_time',
      description: 'Pure naturalness: simple response with no performance anxiety - measuring how close to natural baseline the body moves',
      parameters: { stimulusType: 'gentle-prompt', targetCount: 12, evaluateNaturalness: true, noPerformancePressure: true, baselineComparison: true, minGap: 1500, maxGap: 4000 },
      measures: ['consistency', 'response_time', 'accuracy'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      consistency: 0.4,
      response_time: 0.3,
      accuracy: 0.3,
    },
  },
  minimumTrials: 5,
  estimatedDurationMs: 240000,
  itemPool: [
    { id: 'somatic-turquoise-01', taskType: 'self_report', difficulty: 0.2, parameters: { prompts: ['Sense your body not as a thing but as a field of awareness. What do you notice?'], responseType: 'text', bodyAsConsciousness: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-turquoise-02', taskType: 'scenario', difficulty: 0.25, parameters: { scenarioType: 'body-as-consciousness', responseType: 'text', scenarios: 2, cellularLevel: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-turquoise-03', taskType: 'self_report', difficulty: 0.3, parameters: { prompts: ['Where does your body end and the world begin? Look carefully.'], responseType: 'text', boundaryDissolution: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-turquoise-04', taskType: 'rhythm', difficulty: 0.35, parameters: { beatsPerMinute: 60, beats: 12, tolerance: 0.08, bodyAsAwareness: true, effortless: true }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-turquoise-05', taskType: 'self_report', difficulty: 0.4, parameters: { prompts: ['Feel into a single cell. What does it know?'], responseType: 'text', cellularAwareness: true }, measures: ['depth', 'coherence'] },
    { id: 'somatic-turquoise-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'body-as-consciousness', responseType: 'text', scenarios: 2, boundaryDissolution: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-07', taskType: 'self_report', difficulty: 0.45, parameters: { prompts: ['The body breathes itself. Digests itself. Heals itself. What intelligence is this?'], responseType: 'text', bodyIntelligence: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-08', taskType: 'rhythm', difficulty: 0.5, parameters: { beatsPerMinute: 72, beats: 16, tolerance: 0.06, bodyAsAwareness: true, effortless: true, breathSync: true }, measures: ['accuracy', 'consistency'] },
    { id: 'somatic-turquoise-09', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'body-as-consciousness', responseType: 'text', scenarios: 3, cellularAwareness: true, noSeparation: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-10', taskType: 'self_report', difficulty: 0.55, parameters: { prompts: ['Awareness is not in the body. The body is in awareness. Describe this reversal as felt experience.'], responseType: 'text', nonDualBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'body-boundary-dissolution', responseType: 'text', scenarios: 3, environmentAsBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-12', taskType: 'rhythm', difficulty: 0.6, parameters: { beatsPerMinute: 80, beats: 20, tolerance: 0.05, bodyAsAwareness: true, effortless: true, universalRhythm: true }, measures: ['accuracy', 'consistency', 'integration'] },
    { id: 'somatic-turquoise-13', taskType: 'self_report', difficulty: 0.65, parameters: { prompts: ['The body is made of the same substance as stars. Feel this not as idea but as sensation.'], responseType: 'text', cosmicBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'body-as-consciousness', responseType: 'text', scenarios: 4, cellularAwareness: true, boundaryDissolution: true, cosmicBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-15', taskType: 'self_report', difficulty: 0.7, parameters: { prompts: ['Movement happens. There is no mover. Describe action without an actor in the body.'], responseType: 'text', nonDualBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-16', taskType: 'rhythm', difficulty: 0.75, parameters: { beatsPerMinute: 90, beats: 24, tolerance: 0.04, bodyAsAwareness: true, effortless: true, universalRhythm: true, noDoer: true }, measures: ['accuracy', 'consistency', 'integration'] },
    { id: 'somatic-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'body-boundary-dissolution', responseType: 'text', scenarios: 4, environmentAsBody: true, cosmicBody: true, noSeparation: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'somatic-turquoise-18', taskType: 'self_report', difficulty: 0.8, parameters: { prompts: ['Every atom in your body was forged in a star. Feel the universe feeling itself through this body.'], responseType: 'text', cosmicBody: true, nonDualBody: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'somatic-turquoise-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'body-as-consciousness', responseType: 'text', scenarios: 4, cellularAwareness: true, boundaryDissolution: true, noDoer: true, cosmicBody: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'somatic-turquoise-20', taskType: 'rhythm', difficulty: 0.9, parameters: { beatsPerMinute: 108, beats: 32, tolerance: 0.03, bodyAsAwareness: true, effortless: true, universalRhythm: true, noDoer: true, cosmicBody: true }, measures: ['accuracy', 'consistency', 'integration', 'coherence'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Move without deliberation - the body acts from its own knowing without mental instruction',
      task: {
        id: 'som-turq-probe-agency',
        type: 'reaction_time',
        description: 'Respond from body-knowing alone, no mental deliberation permitted',
        parameters: { stimulusType: 'none', targetCount: 8, selfDetermined: true, noExternalCue: true, measureSpontaneity: true },
        measures: ['consistency', 'response_time'],
      },
      healthyResponse: 'Body moves at its own timing with remarkable consistency; no mind-body split, just unified action arising',
      addictionSignal: 'Subtle performance of spontaneity; trying to be natural which creates artificiality; the body becomes a spiritual project',
      allergySignal: 'Without external cues or mental instruction, body freezes; spontaneous somatic intelligence not yet trusted',
    },
    communion: {
      description: 'Synchronize with another without trying - let bodies find shared rhythm naturally',
      task: {
        id: 'som-turq-probe-communion',
        type: 'rhythm',
        description: 'Find shared timing with NPC partner without verbal coordination',
        parameters: { pattern: [1, 0, 1, 0, 1, 1, 0, 1], bpm: 75, partnerMode: true, communicationAllowed: false, measureEmergentSync: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Bodies find each other without effort; synchrony emerges rather than being created; natural entrainment without trying',
      addictionSignal: 'Forces synchrony through hyper-attunement; cannot let it emerge, must control the connection somatically',
      allergySignal: 'Cannot let body attune to another; somatic isolation persists even when willing',
    },
    eros: {
      description: 'Meet somatic edge without straining - where movement becomes difficult, maintain effortlessness',
      task: {
        id: 'som-turq-probe-eros',
        type: 'rhythm',
        description: 'Complex polyrhythm at the edge of somatic capacity without increasing effort',
        parameters: { pattern: [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0], bpm: 110, trials: 3, measureStrainAtEdge: true },
        measures: ['consistency', 'accuracy', 'response_time'],
      },
      healthyResponse: 'At the edge of difficulty, effort does not increase; the body meets challenge with the same quality as simple movement',
      addictionSignal: 'Seeks somatic difficulty as proof of advancement; pushes body beyond natural capacity, mistaking strain for growth',
      allergySignal: 'At somatic edge, effortlessness shatters and mechanical strain replaces it; transparency only works in comfort zone',
    },
    agape: {
      description: 'Rest in simplest movement with full presence - a tap is just a tap, fully alive',
      task: {
        id: 'som-turq-probe-agape',
        type: 'reaction_time',
        description: 'Simple single tap with complete somatic presence',
        parameters: { stimulusType: 'simple', targetCount: 5, minGap: 2000, maxGap: 4000, measurePresenceQuality: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Simplest movement performed with same luminous quality as complex; body fully alive in the ordinary',
      addictionSignal: 'Simple movement feels insufficient; body restless without complexity or challenge',
      allergySignal: 'Cannot bring presence to simple movement; somatic awareness only activates for special occasions',
    },
  },
};
