/**
 * The authored world seeds — the foundational seeding for the WORLD tier of the
 * world/NPC/scenario + personalization architecture (46 §2's world library, 45 §5 §2).
 *
 * Where `scenarioSeeds.ts` authors each cell's canonical SITUATION (what happens) and
 * `facets/` composes entity TEXTURE (46 §2/§7), these seeds author each cell's canonical
 * PLACE — the stage the situation stands on. The scenario seed is the drama; the world seed is
 * the room it happens in: locus, sensory texture, population, and the quiet tension the place
 * itself exerts. Composition can vary who and how (facets, NPCs, modality angles); the world
 * seed guarantees the WHERE is always written at the encounter's altitude.
 *
 * The load-bearing content rule the user ratified: the permutation of [world, NPC, scenario]
 * components must not produce a stage-incoherent simulation — so every seed carries its own
 * cell and the coherence validator (stageCoherence.ts) treats it as load-bearing for that cell.
 * A Red war-yard never hosts an Amber dialogue as its load-bearing ground; ±1-stage texture
 * (an offhand register, the weather) is the only licensed adjacency.
 *
 * Tags name the place's FLAVOUR domains — every tag resolves in the initial tag store (46 §11
 * invariant 4; validated by the audit below and the G27 gate). Stage altitude is NOT carried in
 * tags: tags are preference vocabulary, stages are developmental altitude (44's lens/altitude
 * separation).
 *
 * Authoring provenance: each seed cites the concept-draft module-spec sections it was grounded
 * in (the facet compiler's provenance discipline, 46 §8 — humans audit content back to the
 * corpus).
 */

import type { Line } from '../domain/Line.js';
import type { Stage } from '../domain/Stage.js';
import type { TagId } from '../world/tags/types.js';
import { ALL_LINES } from '../domain/Line.js';
import { ALL_STAGES } from '../domain/Stage.js';

/** One authored world seed — the cell's canonical place. */
export interface WorldSeed {
  /** `world:{line}:{stage}:authored` — the id the library registers it under. */
  readonly id: string;
  readonly line: Line;
  readonly stage: Stage;
  /** The locus in one breath — where the player stands. Stage-coherent prose. */
  readonly place: string;
  /** The sensory/atmospheric register — what the place sounds, smells, and feels like. */
  readonly texture: string;
  /** The population: who and what lives here (rendered into NPCs by composition, 46 §7). */
  readonly population: string;
  /** What the place itself quietly asks of whoever stands in it (never a metric, Veil-safe). */
  readonly tension: string;
  /** Flavour domains — store-resolved tags that bias ranking (45 §5.3), never altitude. */
  readonly tags: readonly TagId[];
  /** Corpus provenance: which concept-draft module-spec sections ground this seed. */
  readonly groundedIn: string;
}

const SEED_IDS = ['somatic', 'willpower', 'emotional', 'intrapersonal', 'cognitive', 'moral', 'interpersonal', 'spiritual'] as const;
type SeedLine = (typeof SEED_IDS)[number];

/** Capitalized line names matching the domain `Line` type. */
const LINE_NAMES: Record<SeedLine, Line> = {
  somatic: 'Somatic',
  willpower: 'Willpower',
  emotional: 'Emotional',
  intrapersonal: 'Intrapersonal',
  cognitive: 'Cognitive',
  moral: 'Moral',
  interpersonal: 'Interpersonal',
  spiritual: 'Spiritual',
};

/** Convenience builder keeping each entry compact and uniformly shaped. */
function wseed(
  line: SeedLine,
  stage: Stage,
  place: string,
  texture: string,
  population: string,
  tension: string,
  tags: readonly TagId[],
  groundedIn: string,
): WorldSeed {
  return {
    id: `world:${LINE_NAMES[line]}:${stage}:authored`,
    line: LINE_NAMES[line],
    stage,
    place,
    texture,
    population,
    tension,
    tags,
    groundedIn,
  };
}

export const WORLD_SEEDS: readonly WorldSeed[] = [
  // ── Somatic — the body's line ────────────────────────────────────────────────
  wseed('somatic', 'Infrared',
    'The warm dark of the sleeping-shelter before dawn, where the whole room breathes in one slow rhythm.',
    'Packed wool, low embers, the rock of a hammock someone else is keeping moving.',
    'Sleepers stacked like firewood; the night-tender who rocks the fretful ones without waking.',
    'The body learning, before any word for it, that it is safe enough to sleep.',
    ['kindred', 'ritual'],
    'somatic/infrared module-spec §1 (regulation through co-rhythm) §2 (dark-addiction: retreat into sleep)'),
  wseed('somatic', 'Magenta',
    'The drum-circle ground at the village edge, where the fire answers the tide.',
    'Sweat and woodsmoke; drums landing in the sternum; hide masks warm from the fire.',
    'The drummers in their ring, the dancers the drums ride, the elders reading the flames.',
    'Let the body be moved by something larger — or learn exactly where you end.',
    ['ritual', 'music'],
    'somatic/magenta module-spec §1 (ritual body) §2 (dark-allergy: fearing the body\u2019s ecstasy)'),
  wseed('somatic', 'Red',
    'The war-yard and its bone-gym, chalk-lines and iron under an unforgiving sun.',
    'Chalk-dust, blood-salt, the particular silence of people counting someone else\u2019s reps.',
    'The strong and the ones who would be; the armoror who knows who bleeds where.',
    'Power over the body, or the body\u2019s own power — the yard only rewards one of them.',
    ['warfare', 'craft'],
    'somatic/red module-spec §1 (power-body) §2 (dark-addiction: identification with strength)'),
  wseed('somatic', 'Amber',
    'The training field with its white lines and its clock, bodies arranged in ranks.',
    'Whistle-shrills, counted breath, the squeak of drill shoes on pressed gravel.',
    'The drillmaster with the clipboard of standards; the ranks; the one limping at the back.',
    'Form gives the body a spine — and a cage, and the two are hard to tell apart.',
    ['law', 'ritual'],
    'somatic/amber module-spec §1 (the disciplined body) §2 (dark-allergy: contempt for unruly bodies)'),
  wseed('somatic', 'Orange',
    'The performance lab, glass walls both ways, every machine politely glowing.',
    'Cold light, disinfectant, the beep of a heart-rate strap just under the music.',
    'The optimizers and their dashboards; the coach who has seen this plateau before.',
    'Peak numbers on every readout, and a quiet depletion no readout is measuring.',
    ['technology', 'commerce'],
    'somatic/orange module-spec §1 (the optimized body) §2 (golden-addiction: optimization as self-worth)'),
  wseed('somatic', 'Green',
    'The inclusive gym-garden where the equipment bends to the body, not the reverse.',
    'Rust and herbs; laughter with effort in it; handrails worn to shine.',
    'Care-workers, elders, kids underfoot, a rower training for the Para-circuit.',
    'Every body trained where it is — without anyone performing how caring that is.',
    ['medicine', 'nature'],
    'somatic/green module-spec §1 (embodied care) §2 (dark-addiction: attachment to being the caring one)'),
  wseed('somatic', 'Teal',
    'The cliff-top dojo, one chalkboard of living experiments, the sea doing the metronome work.',
    'Wind and salt; chalk-dust on practiced hands; a page of notes pinned by a stone.',
    'Practitioner-researchers comparing self-trials, disagreeing kindly, re-running the week.',
    'Rigor and inner listening as one discipline — the experiment includes the experimenter.',
    ['craft', 'exploration'],
    'somatic/teal module-spec §1 (integral embodiment) §2 (dark-addiction: owning the map of practice)'),
  wseed('somatic', 'Turquoise',
    'The quiet valley at first light, where people come to walk and nothing else.',
    'Bird-call stepping down the slope; dew going to steam; a synchrony of unhurried steps.',
    'Walkers who came to walk — the valley itself the only program.',
    'No practice left to hold; the body was never elsewhere.',
    ['nature', 'ritual'],
    'somatic/turquoise module-spec §1 (everyday embodiment) §2 (golden-addiction: chasing states through the body)'),

  // ── Willpower — the drive/choice line ────────────────────────────────────────
  wseed('willpower', 'Infrared',
    'The sugar-orchard at dusk, every branch heavy, no one watching but the wasps.',
    'Fermented sweetness on the air; sticky bark; wings in the low gold light.',
    'The pickers too small to reach and reaching anyway; the orchard-keeper who pretends not to see.',
    'Want it, take it — the first self the world pushes back on.',
    ['nature', 'kindred'],
    'willpower/infrared module-spec §1 (impulse before will) §2 (dark-addiction: gratification as rule)'),
  wseed('willpower', 'Magenta',
    'The oath-fire pit where the band\u2019s iron ring passes hand to hand over the coals.',
    'Smoke-stung eyes; iron warm from the fire; the held hush before the spoken word.',
    'The oath-keeper who remembers every pledge ever made here; the young bloods; the one who balked last month.',
    'Keep the word because the ring remembers — the will, outsourced to the tribe.',
    ['ritual', 'kindred'],
    'willpower/magenta module-spec §1 (oath-bound will) §2 (dark-allergy: oath-breaking as curse)'),
  wseed('willpower', 'Red',
    'The siege-camp at midnight, walls black against a sky of torches.',
    'Torch-smut; hoof-churned mud; maps pinned by daggers, corners snapping in the wind.',
    'The war-chief counting ladders; restless captains; the fence-sitters deciding by dawn.',
    'Break the gate, or the will breaks first — the camp will not hold still.',
    ['warfare', 'exploration'],
    'willpower/red module-spec §1 (imperious will) §2 (dark-addiction: identification with conquest)'),
  wseed('willpower', 'Amber',
    'The granary-door where the queue waits and the ledger is law.',
    'Chaff-dust in the lamp-glow; ruled columns; the stamp coming down in rhythm.',
    'The steward who has never missed an entry; the queue; one family one stamp short of mercy.',
    'The rules hold the many. The ledger does not have a column for the one.',
    ['law', 'commerce'],
    'willpower/amber module-spec §1 (rule-governed persistence) §2 (dark-allergy: rigidity toward exceptions)'),
  wseed('willpower', 'Orange',
    'The venture floor under its wall of sticky notes, one deadline circled in red.',
    'Espresso and whiteboard marker; keyboard rain; a countdown nobody re-reads aloud anymore.',
    'The founders; the engineer drafting a resignation into a standup note; the metric board doing the deciding.',
    'Win the quarter, lose the why — the will is fast, the direction is someone else\u2019s.',
    ['technology', 'commerce'],
    'willpower/orange module-spec §1 (goal-driven will) §2 (golden-addiction: achievement as worth)'),
  wseed('willpower', 'Green',
    'The round-table hall where every chair is the same height and the minutes read everyone\u2019s name.',
    'Crockery-clink; the paper-scrape of an amendment; the pause that lets the quietest finish.',
    'The rotating facilitator; the patient dissenters; the first-timers learning they are allowed.',
    'A will made of circles — no one leads, everyone steers, and the road is slow.',
    ['kindred', 'law'],
    'willpower/green module-spec §1 (consensual will) §2 (dark-addiction: attachment to consensus)'),
  wseed('willpower', 'Teal',
    'The workshop-lab where the team rewrites its own charter every year and frames the old one.',
    'Whiteboard ghosts under fresh ink; cold tea; morning light on last year\u2019s frame.',
    'Co-authors of their own discipline — the contract everyone in the room signed.',
    'Discipline that serves the whole, chosen rather than imposed, and harder for it.',
    ['craft', 'exploration'],
    'willpower/teal module-spec §1 (self-authoring will) §2 (dark-addiction: owning the integral way)'),
  wseed('willpower', 'Turquoise',
    'The river-port where boats leave with the current and no one argues with the tide.',
    'Rope-creak; gull-cry; water slapping hulls in no hurry at all.',
    'The boat-folk who read wind, load, and hour, and sail when the river says.',
    'Act without strain — and know the moment effort is still a gift.',
    ['nature', 'exploration'],
    'willpower/turquoise module-spec §1 (field-aligned action) §2 (golden-addiction: waiting for signs instead of choosing)'),

  // ── Emotional — the feeling line ─────────────────────────────────────────────
  wseed('emotional', 'Infrared',
    'The nursery-alcove behind the kitchen, where crying is answered before it finishes.',
    'Warm milk and lamplight; the creak of one rocking chair doing all the rocking.',
    'The comforter with the whole night to spare; the fretful ones; the small echo-chamber of it.',
    'A feeling met, or swallowed whole — the room decides which, tonight.',
    ['kindred', 'medicine'],
    'emotional/infrared module-spec §1 (affect regulation) §2 (dark-addiction: comfort-seeking as rule)'),
  wseed('emotional', 'Magenta',
    'The wake-house, where the dead sit among the living for one final night.',
    'Tallow-smoke; the keener\u2019s line of sound; bread passed hand to hand over the coffin.',
    'The mourners in their circle; the children listening at the curtain; the one who cannot cry yet.',
    'Grief held by rite — or worn as a mask that outlives the night.',
    ['ritual', 'kindred'],
    'emotional/magenta module-spec §1 (communal feeling) §2 (dark-allergy: fearing felt grief)'),
  wseed('emotional', 'Red',
    'The longhouse hall where feuds are aired at full volume and tables remember it.',
    'Spilled mead souring in the grain; slammed wood; the held breath of the not-yet-said.',
    'The hothead mid-sentence; the rival sharpening the other side of the argument; the goader refilling cups.',
    'Rage as honest power — and the wake it leaves in the wood.',
    ['warfare', 'kindred'],
    'emotional/red module-spec §1 (passionate assertion) §2 (dark-addiction: identification with intensity)'),
  wseed('emotional', 'Amber',
    'The receiving-parlor where everyone smiles correctly and the clock keeps the rules.',
    'Rosewater; hushed upholstery; the tick of a clock nobody is allowed to look at.',
    'The hostess fluent in every courtesy; the suitor; the child being taught stillness.',
    'Composure holds the room. Where, exactly, did the feeling go?',
    ['law', 'architecture'],
    'emotional/amber module-spec §1 (regulated expression) §2 (dark-allergy: contempt for open emotion)'),
  wseed('emotional', 'Orange',
    'The clinic-office with its mood-apps, its scorecards, its lavender diffuser on a timer.',
    'Lavender over electronics; tablet-glow; a therapist\u2019s trained, paid, neutral nod.',
    'The life-hacker graphing a marriage; the coach; the spreadsheet with a bad week in it.',
    'Optimize the mood, skip the mourning — the dashboard never asks why.',
    ['technology', 'commerce'],
    'emotional/orange module-spec §1 (emotion as performance) §2 (golden-addiction: bypass via positive affect)'),
  wseed('emotional', 'Green',
    'The listening-circle room, cushions worn into honesty, kettle within reach.',
    'Tea-steam; damp tissues; the unhurried silence that belongs to no one.',
    'The circle-holder; the sharers in their order of arrival; the one who finally cries tonight.',
    'Hold everyone\u2019s feeling without dissolving your own inside it.',
    ['kindred', 'medicine'],
    'emotional/green module-spec §1 (empathic attunement) §2 (dark-addiction: attachment to being needed)'),
  wseed('emotional', 'Teal',
    'The journal-desk at a rain-streaked window, where the weather outside matches the pages.',
    'Ink and rain-noise; coffee gone cold on purpose; pages that do not flatter.',
    'The writer meeting her own pattern for the third time this season — and writing it down again.',
    'Feel it fully and see its machinery at once — the two hands of one looking.',
    ['craft', 'exploration'],
    'emotional/teal module-spec §1 (integral feeling) §2 (dark-addiction: analyzing instead of feeling)'),
  wseed('emotional', 'Turquoise',
    'The shore at storm\u2019s edge, far enough out to be moved and safe enough to stay.',
    'Salt-spray; the aftershock of thunder rolling down the coast; vast grey light.',
    'The watcher who came to let the storm pass through, and the storm.',
    'Nothing to fix, everything to feel — the weather is not about you and moves through you anyway.',
    ['nature', 'ritual'],
    'emotional/turquoise module-spec §1 (witnessing feeling) §2 (golden-addiction: serenity as trophy)'),

  // ── Intrapersonal — the self-knowing line ────────────────────────────────────
  wseed('intrapersonal', 'Infrared',
    'The mirror-pool where the child crouches and meets her reflection face to face.',
    'Sun-warmed stone; the ripple that breaks the face and hands it back; a startled gasp.',
    'The child; the pool; whoever is close enough to be found when she looks up.',
    'Is that me? — the first interior question, asked outward.',
    ['nature', 'kindred'],
    'intrapersonal/infrared module-spec §1 (the body-self) §2 (dark-addiction: merging with whatever feels good)'),
  wseed('intrapersonal', 'Magenta',
    'The name-wall in the clan longhouse, names climbing to the soot-dark roof.',
    'Soot-black beams; carved letters worn smooth where hands check them; an elder\u2019s finger tracing.',
    'The name-giver; the one newly added; the generations listening through the wood.',
    'Who I am is who we have been — a self carried in other people\u2019s names.',
    ['ritual', 'kindred'],
    'intrapersonal/magenta module-spec §1 (ancestral identity) §2 (dark-allergy: dread of namelessness)'),
  wseed('intrapersonal', 'Red',
    'The champion\u2019s lodge door, trophy-scarred, opening on the deeds done in its keeping.',
    'Knife-marks crossed with gold leaf gone to flake; the leather-and-oil smell of a held standard.',
    'The champion between feats; the challenger waiting on the bench; the teller whose job the deeds are.',
    'The self is its victories — until the first loss walks in and sits down.',
    ['warfare', 'commerce'],
    'intrapersonal/red module-spec §1 (the heroic self) §2 (dark-addiction: identification with the victorious self)'),
  wseed('intrapersonal', 'Amber',
    'The guild-hall\u2019s rank-board, brass under wax, one face carved above the list.',
    'Brass-polish and paper; the rulebook\u2019s straight spine; the clerk\u2019s discreet cough.',
    'The guild-master above the list; the apprentice below it; the one passed over, again, politely.',
    'The role is mine — and tonight the hall is empty, and the role is not answering.',
    ['law', 'craft'],
    'intrapersonal/amber module-spec §1 (role identity) §2 (dark-allergy: refusing self-examination beyond the role)'),
  wseed('intrapersonal', 'Orange',
    'The home-office with the five-year plan taped at eye level and the plan taped over the mirror.',
    'Highlighter colors; the spines of self-help books leaned like buttresses; espresso reheated twice.',
    'The improver; the plan; the mirror, mostly covered.',
    'An endless upgrade path for a self who never quite arrives at shipping.',
    ['technology', 'commerce'],
    'intrapersonal/orange module-spec §1 (self as project) §2 (golden-addiction: bypass via self-improvement)'),
  wseed('intrapersonal', 'Green',
    'The retreat-cottage where people arrive to be honest and are fed either way.',
    'Woodsmoke; simple meals; shoes surrendered in a row at the door.',
    'The retreat-keeper who asks the second question; the honest ones; the arriving skeptic.',
    'The true self, met where others are the mirror — and the mirror has feelings.',
    ['kindred', 'nature'],
    'intrapersonal/green module-spec §1 (authentic relating) §2 (dark-addiction: attachment to being real)'),
  wseed('intrapersonal', 'Teal',
    'The observation-bench above the inner weather — the balcony room, instruments and no verdicts.',
    'Fog on glass; the tick of quiet instruments; page after page of the same self, re-measured.',
    'The inner cartographer, mapping weather they are also standing in.',
    'Map the self without claiming to be the map — the bench trembles with the effort.',
    ['exploration', 'craft'],
    'intrapersonal/teal module-spec §1 (the witnessing self) §2 (dark-addiction: owning the integral self-model)'),
  wseed('intrapersonal', 'Turquoise',
    'The open window at night — no walls in the room holding anything in particular.',
    'Night-air; a far-off train; coolness arriving on the hands like a visitor who needs nothing.',
    'No one — and everything the night carries through the frame.',
    'No self to fix, no self to lose; the window does not even remember to be a window.',
    ['nature', 'ritual'],
    'intrapersonal/turquoise module-spec §1 (field-identity) §2 (golden-addiction: chasing the unbounded)'),

  // ── Cognitive — the thinking line ────────────────────────────────────────────
  wseed('cognitive', 'Infrared',
    'The shape-nest, where things fit or refuse to, and the floor is the only hypothesis.',
    'Wooden tangrams knocking; warmth; gum on fingers holding the next piece.',
    'The fitter; the keeper who hands down shapes older than anyone using them.',
    'The world is what the hands can prove — no further, not yet.',
    ['craft', 'nature'],
    'cognitive/infrared module-spec §1 (sensorimotor cognition) §2 (dark-addiction: immediate surface grasping)'),
  wseed('cognitive', 'Magenta',
    'The story-tent, where the night\u2019s tale is laid over the stars and both stay put.',
    'Smoke-hole light in one column; patterned hides; a bone-pointer tapping the pattern.',
    'The tale-keeper; the children who correct the tale when it drifts; the stars, keeping their version.',
    'Symbols that think for the tribe — and think back.',
    ['ritual', 'music'],
    'cognitive/magenta module-spec §1 (symbolic cognition) §2 (dark-allergy: rejecting the tribe\u2019s story as nonsense)'),
  wseed('cognitive', 'Red',
    'The map-table under one lamp, the pieces mid-game, the move half-made.',
    'Lamp-oil and its smoke; a gambler\u2019s quiet; the felt of the board eating sound.',
    'The tactician; the rival reading over one shoulder, breathing carefully.',
    'Think three moves ahead of the world — and never let the face show four.',
    ['warfare', 'commerce'],
    'cognitive/red module-spec §1 (tactical cognition) §2 (dark-addiction: identification with being the smartest)'),
  wseed('cognitive', 'Amber',
    'The scriptorium where the copies must match the master to the hairline.',
    'Ruled vellum; the scratch of nibs in tempo; the master\u2019s tap on the shoulder of an errant line.',
    'The copy-master; the scribes; the errant scribe whose \u201cimprovement\u201d is being scraped away.',
    'Truth is what is verifiably repeated — and the margin is where doubt is exiled.',
    ['law', 'craft'],
    'cognitive/amber module-spec §1 (rule-bound reason) §2 (dark-allergy: dismissing other methods as error)'),
  wseed('cognitive', 'Orange',
    'The laboratory bench with its half-crossed predictions pinned under glass.',
    'Glassware ring-marks; the fan\u2019s steady hum; pencil shorthand outrunning the ink.',
    'The experimenter; the rival lab one floor down; the result that came out wrong twice.',
    'The world yields to testable questions — and only slowly to unwelcome answers.',
    ['technology', 'exploration'],
    'cognitive/orange module-spec §1 (scientific cognition) §2 (golden-addiction: understanding as control)'),
  wseed('cognitive', 'Green',
    'The seminar-table with too many chairs and every reading declared situated.',
    'Annotated margins; shared chalk going down to stubs; the chair added last for the absent view.',
    'The relativizers; the quiet one holding the counter-case; the visitor from the other school.',
    'All views have a vantage — including the one declaring it.',
    ['law', 'kindred'],
    'cognitive/green module-spec §1 (contextual cognition) §2 (dark-addiction: attachment to inclusiveness)'),
  wseed('cognitive', 'Teal',
    'The systems-wall where the feedback loops are drawn in yarn and redrawn by morning.',
    'Yarn between pins; cold coffee; the low argument of two domains discovering a shared loop.',
    'The integrator; the domain-hoppers; the wall itself, growing a new level every week.',
    'See the whole without flattening the parts — the yarn is patient, the truth is layered.',
    ['exploration', 'craft'],
    'cognitive/teal module-spec §1 (integrative cognition) §2 (dark-addiction: owning the integral frame)'),
  wseed('cognitive', 'Turquoise',
    'The weather-glass room, where the live charts and the meditation cushion share one desk.',
    'Condensation on the glass; charts updating in the corner of the eye; a single bell marking nothing.',
    'The listener-observer, who reads the data and the room as one continuous text.',
    'Knowing as participation — the instrument includes the one reading it.',
    ['nature', 'ritual'],
    'cognitive/turquoise module-spec §1 (field cognition) §2 (golden-addiction: mistaking the map of oneness for oneness)'),

  // ── Moral — the ethics line ──────────────────────────────────────────────────
  wseed('moral', 'Infrared',
    'The sharing-blanket, where the toys change hands by tally and the tally is sacred.',
    'Wool-scratch; cookie crumbs in the folds; a truck held with two tight hands.',
    'The holder; the coaxer; the blanket itself, the first border ever drawn.',
    'Mine, yours, and the trade that keeps the peace — fairness begins as a barter.',
    ['kindred', 'nature'],
    'moral/infrared module-spec §1 (egocentric fairness) §2 (dark-addiction: taking as rule)'),
  wseed('moral', 'Magenta',
    'The taboo-grove, where the tribe\u2019s forbidden things wait under rope and silence.',
    'Rope-bitten bark; offerings gone soft in the rain; a hush that has weight.',
    'The taboo-keeper with the key no one sees; the tempted youth; the grove.',
    'The tribe\u2019s sacred line — cross it and be cast out; keep it and be kept.',
    ['ritual', 'kindred'],
    'moral/magenta module-spec §1 (mythic-loyal ethics) §2 (dark-allergy: dread of outsiders\u2019 ways)'),
  wseed('moral', 'Red',
    'The duel-ground\u2019s chalk circle at noon, crowds making a dry thunder around it.',
    'Dust-dry mouths; the shuffle of a crowd learning patience; bare knuckles opening.',
    'The duelist; the wronged; the referee who counts to ten with real regret.',
    'Power answers insults — or rises above them, and the circle tests which.',
    ['warfare', 'exploration'],
    'moral/red module-spec §1 (honor ethics) §2 (dark-addiction: identification with honor)'),
  wseed('moral', 'Amber',
    'The judgment-bench under the town clock, where the oath-book never closes.',
    'Ledger bindings; the oath-book\u2019s ribbon; the clerk\u2019s stamp, the day\u2019s metronome.',
    'The judge; the rule-keeper; the offender everyone in the gallery is related to.',
    'Justice by the book — and mercy standing outside in the cold, waiting its turn.',
    ['law', 'commerce'],
    'moral/amber module-spec §1 (law-and-order ethics) §2 (dark-allergy: intolerance of rule-breakers)'),
  wseed('moral', 'Orange',
    'The negotiation-suite where the deals are written, closed, and tomorrow contested.',
    'Leather chairs; pen-clicks; condensation on water glasses nobody drinks.',
    'The closer; the regulator; the whistleblower holding the third copy of something.',
    'Consent and consequence — and the question of who counts the externalities.',
    ['commerce', 'technology'],
    'moral/orange module-spec §1 (contractual ethics) §2 (golden-addiction: outcomes as justification)'),
  wseed('moral', 'Green',
    'The aid-station at the border, where everyone treated is someone\u2019s child.',
    'Disinfectant over wool blankets; a babel of tongues learning one triage word.',
    'The medics; the volunteers; the borders — both sides of them — behind the canvas.',
    'Care with no circle drawn around it, and the ledger of costs nobody shows.',
    ['medicine', 'kindred'],
    'moral/green module-spec §1 (caring ethics) §2 (dark-addiction: attachment to being good)'),
  wseed('moral', 'Teal',
    'The ethics-review room, where every arrow on the chart is traced to its end.',
    'Printouts and cold tea; the long silence after the question that has no owner.',
    'The system-ethicist; the stakeholder choir; the arrow nobody wants to trace.',
    'Do the least harm across the whole web — and be the one who has to say it.',
    ['craft', 'law'],
    'moral/teal module-spec §1 (systemic ethics) §2 (dark-addiction: owning the ethical calculus)'),
  wseed('moral', 'Turquoise',
    'The watershed commons, where every upstream choice is already everyone\u2019s water.',
    'Reed-sound; shared tools racked by the bank; one bucket moving hand to hand.',
    'The commons-keepers, upstream and down, who know whose well their morning washes into.',
    'No separate self to act from — and still, the bucket has to move.',
    ['nature', 'ritual'],
    'moral/turquoise module-spec §1 (participatory ethics) §2 (golden-addiction: acting only from the whole)'),

  // ── Interpersonal — the relationship line ────────────────────────────────────
  wseed('interpersonal', 'Infrared',
    'The fire-circle where the small ones orbit the warm ones in strict, unspoken law.',
    'Smoke shifting with the wind; sparks to flinch from; the gravity of a held hand.',
    'The orbiting child; the warm elder who is the fire\u2019s real keeper.',
    'Closeness is survival — the orbit is the first relationship.',
    ['kindred', 'nature'],
    'interpersonal/infrared module-spec §1 (attachment bonds) §2 (dark-addiction: clinging as connection)'),
  wseed('interpersonal', 'Magenta',
    'The betrothal-yard where two families become one debt, in dyed cloth and drummed steps.',
    'Dye-bright banners; drum-Steps; cousins crowding the courtyard wall.',
    'The couple; the elders who arranged it; the aunt objecting on principle and enjoying it.',
    'Marriage as alliance, love as afterthought — the yard holds both and ranks them.',
    ['kindred', 'ritual'],
    'interpersonal/magenta module-spec §1 (kinship bonds) §2 (dark-allergy: fear of out-group intimacy)'),
  wseed('interpersonal', 'Red',
    'The captain\u2019s quarterdeck, where the pecking order redraws itself daily at sea.',
    'Salt-stiff rope; boot-heel turns; the testing glance that lands and holds one second too long.',
    'The captain; the challenger; the loyal second counting who salutes first.',
    'Rule the ship or be ruled by it — the deck permits no third position.',
    ['warfare', 'exploration'],
    'interpersonal/red module-spec §1 (power relations) §2 (dark-addiction: identification with dominance)'),
  wseed('interpersonal', 'Amber',
    'The drawing-room where the chairs are a hierarchy and everyone reads it at a glance.',
    'Silver teaspoons on porcelain; measured courtesies; the seat by the window, unbeatable.',
    'The host; the favored guest; the slighted one smiling from the far chair.',
    'Know your place — or lose your place; the room has never heard of a third option.',
    ['law', 'architecture'],
    'interpersonal/amber module-spec §1 (station relations) §2 (dark-allergy: contempt for those below station)'),
  wseed('interpersonal', 'Orange',
    'The conference-bar where cards change hands and the lighting flatters the name-tag.',
    'Name-tag glare; cocktail arithmetic; the elevator pitch running in the background like a pump.',
    'The networker; the genuine contact; the used contact, finding out.',
    'Every tie is an asset — and the crowd gets lonelier the better it works.',
    ['commerce', 'technology'],
    'interpersonal/orange module-spec §1 (exchange relations) §2 (golden-addiction: connection as status)'),
  wseed('interpersonal', 'Green',
    'The encounter-group loft, chairs in the round, one silence held on purpose.',
    'Creaking chairs; the tissue box making its rounds; a pause everyone is protecting.',
    'The facilitator; the challenger; the newly open, hearing their own voice say it.',
    'Real meeting requires risk — the round has no hiding seat.',
    ['kindred', 'music'],
    'interpersonal/green module-spec §1 (dialogic relations) §2 (dark-addiction: harmony-keeping)'),
  wseed('interpersonal', 'Teal',
    'The partnership-bench where two crafts build one thing neither could build alone.',
    'Shared tools worn at both grips; alternating hands; the smell of the weld — or the bread.',
    'The co-authors of one work, passing it back and forth without scoring.',
    'The other as a whole person, not a function — the bench teaches it the slow way.',
    ['craft', 'exploration'],
    'interpersonal/teal module-spec §1 (co-creative relations) §2 (dark-addiction: owning the integral partnership)'),
  wseed('interpersonal', 'Turquoise',
    'The two-chair porch at dusk, where the silence is the third guest and no one serves it tea.',
    'Dusk light going blue; katydids; tea going cold, unnoticed and unmissed.',
    'The two who need not speak; the dusk; whatever passes between them without moving.',
    'Presence without grasping — the conversation the room is already having.',
    ['nature', 'ritual'],
    'interpersonal/turquoise module-spec §1 (field relations) §2 (golden-addiction: merging as avoidance)'),

  // ── Spiritual — the meaning line ─────────────────────────────────────────────
  wseed('spiritual', 'Infrared',
    'The ember-nook where the first \u201csomeone up there\u201d is whispered into being.',
    'Ember-glow on a drawn-up knee; hushed breath; a charm on a string, held like a rope.',
    'The child; the charm; the whispered someone, so recently invented and already in charge.',
    'The first feeling of protection from beyond the room.',
    ['ritual', 'kindred'],
    'spiritual/infrared module-spec §1 (the protective numinous) §2 (dark-addiction: magic as transaction)'),
  wseed('spiritual', 'Magenta',
    'The spirit-house at the field\u2019s edge, where the offerings are left and the tenants unseen.',
    'Flower garlands fading by the hour; incense-stubs in rank; rain-polished little woodwork.',
    'The offering-maker with the exact right fruit; the unseen tenants, never photographed.',
    'A world crowded with presences to be honored — and to be very careful with.',
    ['ritual', 'nature'],
    'spiritual/magenta module-spec §1 (animistic devotion) §2 (dark-allergy: dread of offended spirits)'),
  wseed('spiritual', 'Red',
    'The war-altar where the victory is dedicated before the wounded are counted.',
    'The smoke of thank-offerings; blood drying on the stone; the trophy stack in the sun.',
    'The war-priest with his anointing; the triumphant captain; the uneasy seer who reads the smoke differently.',
    'God as sponsor of conquest — the altar keeps what the army brings it.',
    ['warfare', 'ritual'],
    'spiritual/red module-spec §1 (power-spirituality) §2 (dark-addiction: identification with the god-image)'),
  wseed('spiritual', 'Amber',
    'The liturgical hour at the order\u2019s chapel — the same words, the same gestures, centuries of the same.',
    'Candle-flames at attention; the chant\u2019s worn groove; stone keeping every repetition.',
    'The liturgist who never varies; the young monk hearing it fresh for the first time.',
    'Tradition as the vessel that holds — until it is mistaken for the water.',
    ['ritual', 'law'],
    'spiritual/amber module-spec §1 (mythic-membership faith) §2 (dark-allergy: rejecting other paths as godless)'),
  wseed('spiritual', 'Orange',
    'The marketplace of practices, where the app-shrine glows between the retreat brochures.',
    'Incense sold in bulk; screens counting streaks; a biofeedback headband boxed like jewelry.',
    'The practice-seller; the seeker-consumer with the portfolio of techniques and no compass.',
    'Real doors opened — and the seeker growing heavier with each key.',
    ['commerce', 'technology'],
    'spiritual/orange module-spec §1 (individuated practice) §2 (golden-addiction: bypass via achievement)'),
  wseed('spiritual', 'Green',
    'The interfaith shelter\u2019s kitchen, where five prayers argue upstairs and the pot is unmistakably holy.',
    'Steam and chopping; the murmur of doctrine through the floor; the smell that ends the argument.',
    'The five prayer-leaders; the volunteers who never argue; the strangers eating as one table.',
    'Plurality honored, the shared heart met in service — the soup has no denomination.',
    ['medicine', 'kindred'],
    'spiritual/green module-spec §1 (compassionate pluralism) §2 (dark-addiction: attachment to being the caring one)'),
  wseed('spiritual', 'Teal',
    'The contemplative-ecology station, where monks and scientists share one question and one kettle.',
    'Sensor cables among the moss; dawn mist on the instruments; the kettle\u2019s small agreement.',
    'The monk-scientist pair, trading vocabularies; the forest, the silent third party.',
    'Practice and science as two languages for one living whole — each changed by the translation.',
    ['nature', 'craft'],
    'spiritual/teal module-spec §1 (nature-mysticism with rigor) §2 (dark-addiction: owning the integral map)'),
  wseed('spiritual', 'Turquoise',
    'The ordinary afternoon courtyard with nothing missing from it.',
    'Tea; traffic-noise; sun on swept stone; the whole field of it, unimproved.',
    'The friend who is also the whole field; the tea; the afternoon, requiring nothing.',
    'Spirit not as elsewhere but as the is-ness that was never absent.',
    ['ritual', 'nature'],
    'spiritual/turquoise module-spec §1 (everyday nonduality) §2 (golden-addiction: peak-state chasing disguised as presence)'),
];

/** Stages or lines without a world seed row above are compile errors, not silent gaps. */
export function assertWorldSeedCoverage(): void {
  const have = new Set(WORLD_SEEDS.map((s) => `${s.line}:${s.stage}`));
  const missing: string[] = [];
  for (const line of ALL_LINES) {
    for (const stage of ALL_STAGES) {
      if (!have.has(`${line}:${stage}`)) missing.push(`${line}:${stage}`);
    }
  }
  if (missing.length > 0) {
    throw new Error(`world seeds: missing cells [${missing.join(', ')}] — 64/64 coverage is a compile-time invariant`);
  }
}

assertWorldSeedCoverage();
