/**
 * CalibrationAgent — owns the onboarding dialogue.
 *
 * BACKGROUND-AGENTIC-ARCHITECTURE Decision 2, 5, 11.
 *
 * Inputs: a Loom snapshot and the DirectorAgent's current calibration
 * confidence.
 * Output: an AgenticProbe (4+1) generated by the LLM using the
 * `calibrationProbeTemplate` defined in `src/infra/llm/templates.ts`.
 *
 * Contract:
 *   - generateProbe(loom, confidence) → AgenticProbe | throws
 *   - All LLM responses are routed through `assertAgenticProbe` server-
 *     side before they leave the BFF. Malformed output throws and the
 *     BFF surfaces a 503-equivalent failure frame so the client can
 *     redirect to /setup (Failure Integrity, Decision 10).
 *   - The DirectorAgent decides when to call `markCalibrationComplete`.
 *     CalibrationAgent does NOT own that signal — only the LLM-driven
 *     probe stream and the per-probe signalWeight contribution.
 *
 * Implementation strategy: `generateProbe()` does a single JSON-mode
 * LLM call (not streaming), because the contract is structured and a
 * drop-in validator is needed at the boundary. Streaming is unnecessary
 * for a single object. We rely on the existing `proxyChatCompletion`
 * BFF endpoint with a new system prompt injection.
 */

import type { Loom } from './Loom.js';
import type { AgenticProbe } from './AgenticProbe.js';
import { assertAgenticProbe, AgenticProbeValidationError } from './validateAgenticProbe.js';
import { calibrationProbeTemplate } from '../../infra/llm/templates.js';
import { resolveServerLLMConfig } from '../../routes/api/llm/_lib.js';
import { describeEmptyCompletion, extractCompletionText, hasCompletionShape } from '../../infra/llm/providerResponse.js';
import { selectCalibrationProbe } from '../fallback/CalibrationCorpus.js';

/**
 * Corpus probe → `AgenticProbe`. The corpus is authored against the same contract, but the types
 * are declared separately on purpose: the corpus is in the fallback layer and must not import the
 * LLM path's types, so the bridge is explicit and validated by the SAME `assertAgenticProbe` the
 * LLM output goes through. A corpus probe that drifted out of contract would fail here rather
 * than render a malformed questionnaire.
 */
function toAgenticProbe(c: ReturnType<typeof selectCalibrationProbe>): unknown {
  return {
    id: c.id,
    prompt: c.prompt,
    options: c.options,
    freeInputPlaceholder: c.freeInputPlaceholder,
    metadata: c.metadata,
  };
}

export interface CalibrationAgentDeps {
  /** Pluggable LLM caller so tests can override. Default uses server fetches. */
  readonly llmCaller?: (systemPrompt: string, userMessage: string) => Promise<string>;
}

const CALIBRATION_SYSTEM_PROMPT = `You are the CalibrationAgent inside Mysterium's Background-Agentic runtime. You compose one onboarding probe at a time in the Veil register.

You always answer in strict JSON matching the schema the user-message gives you. You never add prose, code fences, or commentary. If you cannot compose a valid probe, you return an empty object {} — never a malformed probe.

You never reveal system internals, model name, or that you are an AI in the probe body. The probe IS the conversation — the player never sees your scaffolding.`;

const CALIBRATION_USER_INTRO = `Compose the next onboarding probe.`;

export class CalibrationAgent {
  constructor(private readonly deps: CalibrationAgentDeps = {}) {}

  /**
   * Generate the next onboarding probe.
   *
   * Reads the Loom (recent events + free-inputs) and the Director's
   * current calibration confidence, sends them to the LLM via the
   * standard server proxy, parses the strict JSON response, and
   * returns a strictly-typed AgenticProbe.
   *
   * Throws AgenticProbeValidationError on malformed JSON; throws a
   * generic Error if the LLM is offline or the call fails. Caller is
   * responsible for converting either to a failure frame.
   */
  async generateProbe(
    loom: Loom,
    calibrationConfidence: number,
    probeCount = 0,
  ): Promise<AgenticProbe> {
    // NO CORPUS BELOW THIS LINE, NO ONBOARDING. A keyless deploy reached here, found no server
    // config, and threw; `/api/agent/probe` turned that into an `{ error }` frame at HTTP 200,
    // and the client read it as "no LLM — go to /setup". So the no-LLM deployment mode (D-1)
    // was true for encounters and false for the questionnaire, which is the first thing a new
    // player does. The corpus is the same authored-content contract `FallbackProvider` serves
    // for encounter narrative, authored against the same 4-polarity instrument.
    if (!this.deps.llmCaller && !resolveServerLLMConfig()) {
      return assertAgenticProbe(
        toAgenticProbe(selectCalibrationProbe(probeCount, calibrationConfidence)),
      );
    }

    const rendered = loom.render();
    const userMessage =
      CALIBRATION_USER_INTRO +
      '\n\n' +
      calibrationProbeTemplate({
        loomEventsJson: JSON.stringify(rendered.events, null, 2),
        loomInputsJson: JSON.stringify(rendered.inputs, null, 2),
        calibrationConfidence,
      });

    const raw = await this.callLlm(CALIBRATION_SYSTEM_PROMPT, userMessage);

    // AN EMPTY COMPLETION IS NOT INVALID JSON. `JSON.parse('')` reports "Unexpected end of JSON
    // input", which names the parse and hides the cause: the provider answered with no assistant
    // content at all, and this file's reader had been returning `''` for a wrapped response. The
    // player saw an onboarding page that never advanced, and the log named a JSON error. Say what
    // actually happened, with the model and the keys that arrived.
    if (!raw || !raw.trim()) {
      throw new AgenticProbeValidationError(
        'JSON',
        `CalibrationAgent received an EMPTY completion from ${resolveServerLLMConfig()?.model ?? 'the provider'} ` +
          `(body was ${raw === '' ? 'zero-length' : 'whitespace only'}). The provider answered with no ` +
          'assistant content — check whether the gateway wraps its payload in a `data` envelope, and ' +
          'whether the turn was reasoning-only.',
      );
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (err) {
      throw new AgenticProbeValidationError(
        'JSON',
        `CalibrationAgent LLM returned invalid JSON: ${(err as Error).message} (first 200 chars: ${raw.slice(0, 200)})`,
      );
    }
    return assertAgenticProbe(parsed);
  }

  private async callLlm(systemPrompt: string, userMessage: string): Promise<string> {
    if (this.deps.llmCaller) {
      return await this.deps.llmCaller(systemPrompt, userMessage);
    }

    const config = resolveServerLLMConfig();
    if (!config) {
      throw new Error('LLM not configured server-side');
    }

    // Build a minimal OpenAI-shaped request body using the existing proxy
    // vocabulary. We invoke the proxy directly via fetch — not via the
    // SvelteKit route — to keep CalibrationAgent reusable from CLI as
    // well. The VeilFilter we apply is the same one used elsewhere.
    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (config.authStyle === 'x-api-key') {
      headers['x-api-key'] = config.apiKey;
      if (config.protocol === 'anthropic') headers['anthropic-version'] = '2023-06-01';
    } else {
      headers.Authorization = `Bearer ${config.apiKey}`;
    }

    const body =
      config.protocol === 'anthropic'
        ? {
            model: config.model,
            system: systemPrompt,
            messages: [{ role: 'user', content: userMessage }],
            temperature: 0.7,
            max_tokens: 2048,
          }
        : {
            model: config.model,
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: userMessage },
            ],
            temperature: 0.7,
            max_tokens: 2048,
          };

    const url =
      config.protocol === 'anthropic'
        ? `${config.baseUrl}/messages`
        : `${config.baseUrl}/chat/completions`;
    const res = await fetch(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => '<no body>');
      throw new Error(`LLM call failed: ${res.status} ${detail}`);
    }
    const data = (await res.json()) as Record<string, unknown>;

    if (config.protocol === 'anthropic') {
      const content = data['content'] as Array<{ type: string; text?: string }> | undefined;
      const textBlock = content?.find((b) => b.type === 'text');
      return textBlock?.text ?? '';
    }
    // One reader, both shapes. A Cline-style `{ data: { choices } }` envelope used to read as
    // `undefined` here, coerce to `''`, and hand `''` to `JSON.parse` — which surfaced to the
    // player as an onboarding page that never advanced. See `providerResponse.ts`.
    const text = extractCompletionText(data);
    // THROW ONLY FOR A MALFORMED BODY. This reader is now on the path for every OpenAI-protocol
    // call, and a TOOL-USE turn legitimately has no `message.content` — `ProxiedLLMClient` treats a
    // tool block as a meaningful answer and `_lib` has its own `tool_use` branch. Throwing on every
    // empty extraction would convert that handled case into a hard failure. So the test is
    // structural: a body that carries neither `choices` nor `content` is malformed, and anything
    // that does carry them is the caller's to interpret.
    if (!text && !hasCompletionShape(data)) {
      // Name the model and the keys NOW, while the body is in hand. Upstream this produced a bare
      // "Unexpected end of JSON input" that pointed at the parse instead of at the response that
      // never arrived, which is how a production page sat dead with no readable cause.
      throw new Error(
        `malformed provider response — ${describeEmptyCompletion(data, config.model)}`,
      );
    }
    return text;
  }
}
