import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualTeal: StageAssessment = {
  line: 'Spiritual',
  stage: 'Teal',
  tasks: [
    {
      id: 'spir-teal-paradox',
      type: 'value_ranking',
      description: 'Value-coherence under paradox: hold values when logic says they contradict',
      parameters: { values: 6, temptationType: 'paradox-challenge', trials: 4, paradoxLevel: 'high' },
      measures: ['coherence', 'consistency', 'depth'],
    },
    {
      id: 'spir-teal-integral',
      type: 'llm_dialogue',
      description: 'Hold values that transcend AND include lower stages',
      parameters: { prompt: 'How can you honor your tradition AND transcend it? Is that not contradictory?', maxResponseLength: 600 },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      coherence: 0.4,
      depth: 0.3,
      consistency: 0.3,
    },
    llmRubric:
      'Score for integral/vision-logic spiritual reasoning. At Teal, values include paradox - they transcend yet include all previous stages. Coherence: can they hold paradox without collapse? Depth: do they demonstrate genuine trans-rational knowing? Consistency: do values hold even when logic fails?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 270000,
  itemPool: [
    { id: 'spiritual-turquoise-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'non-dual-glimpse', responseType: 'text', scenarios: 2, stateShift: 'subtle' }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-teal-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'Describe a moment when the boundary between you and the world became thin.', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-teal-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'trans-rational-knowing', responseType: 'text', scenarios: 2, beyondConcept: true }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-teal-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'What do you know that you cannot prove or explain? How do you know it?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-teal-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'integral-practice', responseType: 'text', scenarios: 2, practiceType: 'body-mind-spirit' }, measures: ['depth', 'integration'] },
    { id: 'spiritual-teal-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'How do you integrate a spiritual insight that contradicts your rational understanding?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'non-dual-glimpse', responseType: 'text', scenarios: 3, stateShift: 'causal' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-teal-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'Describe the difference between a spiritual experience and spiritual development. Which matters more?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'spiritual-teal-09', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'trans-rational-knowing', responseType: 'text', scenarios: 3, paradoxPresent: true }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'spiritual-teal-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'What is the relationship between emptiness and form in your direct experience?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-teal-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'integral-practice', responseType: 'text', scenarios: 3, practiceType: 'shadow-and-spirit' }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'spiritual-teal-12', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'How do you practice spiritually without making spirituality into another ego project?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'spiritual-turquoise-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'non-dual-glimpse', responseType: 'text', scenarios: 3, stateShift: 'non-dual', sustainDuration: true }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'spiritual-teal-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Describe knowing that is prior to the knower. Not what you know, but the knowing itself.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-teal-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'trans-rational-knowing', responseType: 'text', scenarios: 4, multipleWays: true }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'spiritual-teal-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'What is the difference between witnessing awareness and being awareness? Can you demonstrate the shift?', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'integral-practice', responseType: 'text', scenarios: 4, practiceType: 'non-dual-in-daily', embodied: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'spiritual-teal-18', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'The sacred and the mundane are not-two. Describe washing dishes from this realization.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'non-dual-glimpse', responseType: 'text', scenarios: 4, stateShift: 'non-dual', stabilization: true }, measures: ['depth', 'coherence', 'consistency', 'integration'] },
    { id: 'spiritual-teal-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'Describe the taste of awareness aware of itself. Use no spiritual vocabulary.', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Hold value-paradox without external support',
      task: {
        id: 'spir-teal-probe-agency',
        type: 'value_ranking',
        description: 'Maintain values under paradox independently',
        parameters: { values: 4, temptationType: 'paradox-challenge', soloMode: true },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Holds paradox with personal stability',
      addictionSignal: 'Clings to paradox as identity, cannot be simple',
      allergySignal: 'Collapses paradox into either/or',
    },
    communion: {
      description: 'Share paradoxical value-holding with NPC',
      task: {
        id: 'spir-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'Share how you hold paradox with NPC',
        parameters: { prompt: 'That makes no logical sense. How do you hold both?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares paradox without needing other to get it',
      addictionSignal: 'Forces paradox-awareness on unprepared other',
      allergySignal: 'Cannot communicate paradoxical knowing',
    },
    eros: {
      description: 'Face ultimate paradox: value and valuelessness',
      task: {
        id: 'spir-teal-probe-eros',
        type: 'scenario',
        description: 'Face paradox of holding values while knowing all values are empty',
        parameters: { scenarioType: 'ultimate-paradox', responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Holds ultimate paradox without collapse or inflation',
      addictionSignal: 'Spiritual inflation, uses paradox to avoid commitment',
      allergySignal: 'Refuses to engage with emptiness of values',
    },
    agape: {
      description: 'Return to simplest value with devotion',
      task: {
        id: 'spir-teal-probe-agape',
        type: 'value_ranking',
        description: 'Return to simplest value with full devotion',
        parameters: { values: 2, temptationType: 'none', complexity: 'minimal' },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Returns to simple value with deep devotion',
      addictionSignal: 'Refuses simplicity as beneath integral awareness',
      allergySignal: 'Cannot hold value with devotion at any level',
    },
  },
};
