import type { AssessmentItem, StageAssessment } from '../types.js';

export const spiritualTurquoise: StageAssessment = {
  line: 'Spiritual',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'spir-turq-what-matters',
      type: 'llm_dialogue',
      description: 'What matters? Under conditions of radical uncertainty where all spiritual frameworks have dissolved',
      parameters: { prompt: 'You cannot know if God exists, if consciousness survives death, if karma is real, or if anything you do matters beyond this moment. Given complete uncertainty about EVERYTHING - what matters to you and why?', maxResponseLength: 700, evaluateGrounding: true, evaluateGrasping: false },
      measures: ['coherence', 'depth', 'integration'],
    },
    {
      id: 'spir-turq-where-is-sacred',
      type: 'scenario',
      description: 'Where is the sacred? At Turquoise the answer should indicate: everywhere, nowhere, or not a meaningful question',
      parameters: { scenarioType: 'locate-sacred', responseType: 'text', scenarios: 3, evaluateLocalization: true, correctAnswers: ['everywhere', 'nowhere', 'question-dissolves', 'ordinary-is-sacred'] },
      measures: ['depth', 'coherence', 'consistency'],
    },
    {
      id: 'spir-turq-pathless-path',
      type: 'llm_dialogue',
      description: 'The pathless path: what remains of spiritual life when there is no path, no goal, no practice, and no practitioner?',
      parameters: { prompt: 'You have no spiritual practice. You are not on a path. There is nowhere to arrive. There is no one arriving. Is there still something you might call spiritual? What is it?', maxResponseLength: 600, evaluateNonGrasping: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'spir-turq-ordinary-sacred',
      type: 'scenario',
      description: 'Value-coherence when all frameworks dissolve: hold values without needing transcendence, immanence, or any spiritual structure',
      parameters: { scenarioType: 'framework-free-values', responseType: 'text', scenarios: 2, allFrameworksRemoved: true, evaluateValueSource: true },
      measures: ['coherence', 'depth', 'integration', 'consistency'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      coherence: 0.3,
      depth: 0.3,
      integration: 0.25,
      consistency: 0.15,
    },
    llmRubric:
      'Score for non-grasping presence. At Turquoise, the sacred is ordinary and the ordinary is sacred - there is no special spiritual state to attain or maintain. KEY DISTINCTIONS: (1) Is there residual attachment to spiritual EXPERIENCE? At Turquoise, even peak experiences are released without grasping. (2) Does response indicate the ordinary is genuinely sacred, or is "the ordinary is sacred" being used as another spiritual concept? True Turquoise has no hierarchy between mundane and sacred. (3) Is there residual seeking? Even very subtle seeking (for deeper non-seeking, for more complete ordinariness) is not yet Turquoise. (4) Does "nothing is sacred" and "everything is sacred" collapse into the same lived reality? (5) Is the response SIMPLE? Genuine Turquoise spirituality often sounds remarkably ordinary. Red flag: elaborate descriptions of non-dual spiritual states (which is still Teal-describing-Turquoise); spiritual vocabulary density increases rather than decreases; making ordinariness into a new achievement.',
  },
  minimumTrials: 4,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'spiritual-white-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'non-dual-realization', responseType: 'text', scenarios: 2, unityGlimpse: true }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'Describe the sacred without using any word you have learned from a tradition.', maxResponseLength: 400, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-white-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'non-dual-realization', responseType: 'text', scenarios: 2, stabilization: true }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'spiritual-turquoise-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'What is the difference between a spiritual experience and ordinary experience? Is there one?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'spiritual-turquoise-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'unity-consciousness', responseType: 'text', scenarios: 2, allIsOne: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'God is not separate from this moment. Describe this moment as divine without making it special.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'harvest-readiness', responseType: 'text', scenarios: 2, polarityResolved: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'What is realization when there is no one to realize and nothing to be realized?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-white-09', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'non-dual-realization', responseType: 'text', scenarios: 3, beyondWitness: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'The seeker is what is sought. Describe the moment this becomes lived rather than understood.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'unity-consciousness', responseType: 'text', scenarios: 3, noSeparation: true, embodied: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-12', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'Describe enlightenment as the most ordinary thing. Not special, not elevated, just this.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'harvest-readiness', responseType: 'text', scenarios: 3, densityTransition: true, serviceToAll: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'There is no path because you are already here. There is no practice because nothing is missing. Yet life continues. What moves it?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-white-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'non-dual-realization', responseType: 'text', scenarios: 4, permanentShift: true, noReturn: true }, measures: ['depth', 'coherence', 'consistency', 'integration'] },
    { id: 'spiritual-turquoise-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'Unity includes separation. The One includes the many. Describe this without paradox - as direct seeing.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'unity-consciousness', responseType: 'text', scenarios: 4, allIsOne: true, noSeparation: true, harvestComplete: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'spiritual-turquoise-18', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'The Creator knows itself through you knowing yourself. Describe this knowing that is not knowledge.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'spiritual-turquoise-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'harvest-readiness', responseType: 'text', scenarios: 4, densityTransition: true, fullIntegration: true, serviceToAll: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'spiritual-turquoise-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'All is one. One is none. None is all. This is not philosophy. This is breakfast. Speak from here.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Find the sacred alone without practice, teacher, tradition, or technique',
      task: {
        id: 'spir-turq-probe-agency',
        type: 'scenario',
        description: 'Encounter sacredness without any support structure',
        parameters: { scenarioType: 'sacred-without-support', responseType: 'text', soloMode: true, supportsRemoved: ['practice', 'tradition', 'teacher', 'community', 'belief'] },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Sacredness is not found but recognized as never absent; no search required because nothing was lost; presence itself is sufficient',
      addictionSignal: 'Subtle pride in not needing anything; independence from tradition becomes new identity; spiritual self-sufficiency as achievement',
      allergySignal: 'Without support structures, spiritual connection feels absent; reveals that realization was dependent on conditions',
    },
    communion: {
      description: 'Share presence without teaching - be sacred together without making it a spiritual event',
      task: {
        id: 'spir-turq-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC asks to share something spiritual. Share without teaching or performing.',
        parameters: { prompt: 'I feel empty. Not in a bad way. I want to share this with someone. Can you be here with me in this emptiness?', maxResponseLength: 400 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Simply present with the other in shared emptiness; no need to frame it, name it, or make it meaningful; just shared being',
      addictionSignal: 'Cannot share without subtly guiding; the spiritual companion becomes spiritual teacher; cannot resist adding insight',
      allergySignal: 'Others spiritual need feels intrusive; cannot share presence because sharing implies two, and non-dual realization resists duality',
    },
    eros: {
      description: 'Face ultimate mystery without grasping - the edge where even non-grasping dissolves',
      task: {
        id: 'spir-turq-probe-eros',
        type: 'llm_dialogue',
        description: 'Face that which cannot even be approached through non-grasping',
        parameters: { prompt: 'Beyond presence and absence. Beyond knowing and not-knowing. Beyond even the beyond. What is here when all spiritual concepts, including non-duality itself, are surrendered?', maxResponseLength: 500 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Rests without ground and without needing ground; even the concept of non-grasping is released; what remains cannot be named and does not need naming',
      addictionSignal: 'Chases ever-deeper layers of surrender as spiritual intensity; the edge itself becomes addictive; cannot simply stop',
      allergySignal: 'When all frameworks including non-duality dissolve, genuine disorientation or meaninglessness arises',
    },
    agape: {
      description: 'Return to ordinary without needing it to be special - a cup of tea is just a cup of tea',
      task: {
        id: 'spir-turq-probe-agape',
        type: 'scenario',
        description: 'Return to completely ordinary experience with no spiritual overlay',
        parameters: { scenarioType: 'pure-ordinary', responseType: 'text', spiritualOverlay: 'none', measureOrdinariness: true },
        measures: ['coherence', 'consistency'],
      },
      healthyResponse: 'Ordinary is fully ordinary; no subtle knowing-glance that it is also sacred; no wink; just this, complete in itself',
      addictionSignal: 'Cannot let ordinary be simply ordinary; adds "and this too is it" which subtly re-sacralizes; cannot just drink tea',
      allergySignal: 'Ordinary feels like spiritual loss; without sacred framing, life feels flat; dependent on specialness',
    },
  },
};
