import type { AssessmentItem, StageAssessment } from '../types.js';

export const intrapersonalTeal: StageAssessment = {
  line: 'Intrapersonal',
  stage: 'Teal',
  tasks: [
    {
      id: 'intra-teal-witness',
      type: 'scenario',
      description: 'Witness perspective: observe self from meta-position',
      parameters: { scenarioType: 'witness-self', responseType: 'text', scenarios: 3 },
      measures: ['depth', 'metacognition', 'coherence'],
    },
    {
      id: 'intra-teal-disidentify',
      type: 'llm_dialogue',
      description: 'Dis-identification: describe self without identifying with content',
      parameters: { prompt: 'Who are you when you are not your thoughts, roles, or feelings?', maxResponseLength: 600 },
      measures: ['depth', 'metacognition', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      depth: 0.3,
      metacognition: 0.3,
      coherence: 0.2,
      self_correction: 0.2,
    },
  },
  minimumTrials: 3,
  estimatedDurationMs: 270000,
  itemPool: [
    { id: 'intrapersonal-teal-01', taskType: 'self_report', difficulty: 0.2, parameters: { prompts: ['Describe what is observing your thoughts right now.'], responseType: 'text', timeoutMs: 60000 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-teal-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'What remains of you when you stop identifying with your roles?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-teal-03', taskType: 'self_report', difficulty: 0.3, parameters: { prompts: ['Notice the witness. Now notice what notices the witness.'], responseType: 'text', timeoutMs: 60000 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-teal-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'Describe a part of yourself you have been avoiding integrating. What does it need?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-teal-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'identity-fluidity', responseType: 'text', scenarios: 2, identityShift: true }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-teal-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'Who are you when you are not being anyone in particular?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-teal-07', taskType: 'self_report', difficulty: 0.45, parameters: { prompts: ['Describe the boundary between you and not-you. Is it fixed?'], responseType: 'text', timeoutMs: 60000 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-teal-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'shadow-integration', responseType: 'text', scenarios: 2, shadowType: 'golden' }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'intrapersonal-teal-09', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'What is the relationship between the one who witnesses and the one who acts? Are they the same?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-teal-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'identity-fluidity', responseType: 'text', scenarios: 3, multipleSelves: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-teal-11', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'Describe a shadow you have integrated. How did the integration change your sense of self?', maxResponseLength: 500 }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'intrapersonal-teal-12', taskType: 'self_report', difficulty: 0.6, parameters: { prompts: ['What is your identity made of? Can you find its edges?'], responseType: 'text', timeoutMs: 60000 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-teal-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'shadow-integration', responseType: 'text', scenarios: 3, shadowType: 'dark', witnessRequired: true }, measures: ['depth', 'integration', 'self_correction'] },
    { id: 'intrapersonal-teal-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'You discover that your witness consciousness has its own shadow. What is it?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'integration'] },
    { id: 'intrapersonal-teal-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'identity-fluidity', responseType: 'text', scenarios: 3, dissolutionPresent: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-teal-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'Describe the experience of being multiple selves simultaneously without fragmentation.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'intrapersonal-teal-17', taskType: 'self_report', difficulty: 0.8, parameters: { prompts: ['What is the self that includes all your selves? Describe it without making it another self.'], responseType: 'text', timeoutMs: 90000 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-teal-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'shadow-integration', responseType: 'text', scenarios: 4, shadowType: 'both', witnessRequired: true }, measures: ['depth', 'integration', 'complexity_handled'] },
    { id: 'intrapersonal-teal-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'The witness itself is a construction. What remains when even witnessing is released?', maxResponseLength: 600 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-teal-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'identity-fluidity', responseType: 'text', scenarios: 4, fullSpectrum: true, witnessDissolving: true }, measures: ['depth', 'metacognition', 'coherence', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Access witness perspective without guidance',
      task: {
        id: 'intra-teal-probe-agency',
        type: 'scenario',
        description: 'Access meta-perspective on self independently',
        parameters: { scenarioType: 'witness-self', responseType: 'text', soloMode: true },
        measures: ['depth', 'metacognition'],
      },
      healthyResponse: 'Accesses witness perspective with own stability',
      addictionSignal: 'Dissociates, uses witness as avoidance',
      allergySignal: 'Cannot access meta-position without guidance',
    },
    communion: {
      description: 'Share witness perspective with NPC',
      task: {
        id: 'intra-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'Share what witness perspective reveals to NPC',
        parameters: { prompt: 'What do you see when you watch yourself from above?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Shares meta-perspective without losing ground',
      addictionSignal: 'Uses witness to avoid genuine relating',
      allergySignal: 'Cannot share inner witness with another',
    },
    eros: {
      description: 'Dis-identify from even the witness itself',
      task: {
        id: 'intra-teal-probe-eros',
        type: 'llm_dialogue',
        description: 'Who watches the watcher?',
        parameters: { prompt: 'You are watching yourself. But who is watching the watcher?', maxResponseLength: 500 },
        measures: ['depth', 'metacognition'],
      },
      healthyResponse: 'Reaches toward recursive self-awareness',
      addictionSignal: 'Infinite regress, cannot land anywhere',
      allergySignal: 'Refuses recursive self-inquiry',
    },
    agape: {
      description: 'Return to simple self-report with presence',
      task: {
        id: 'intra-teal-probe-agape',
        type: 'self_report',
        description: 'Return to simple statement of what you are',
        parameters: { prompts: ['What are you, right now?'], responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Returns to simple self-awareness with love',
      addictionSignal: 'Refuses simple self-report as naive',
      allergySignal: 'Cannot engage with self at any level',
    },
  },
};
