import type { AssessmentItem, StageAssessment } from '../types.js';

export const intrapersonalTurquoise: StageAssessment = {
  line: 'Intrapersonal',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'intra-turq-describe-without',
      type: 'llm_dialogue',
      description: 'Describe yourself without using roles, traits, or history - the paradox of self-description at the non-dual level',
      parameters: { prompt: 'Describe who you are. You may not use roles (parent, worker, friend), traits (kind, smart, creative), or personal history. What remains?', maxResponseLength: 700, evaluateResidualIdentification: true, evaluateParadoxComfort: true },
      measures: ['depth', 'coherence', 'metacognition', 'integration'],
    },
    {
      id: 'intra-turq-who-is-aware',
      type: 'llm_dialogue',
      description: 'Who is aware right now? Pointing-out instruction - not "what are you aware of" but "who/what IS the awareness?"',
      parameters: { prompt: 'Right now, you are aware. But WHO is aware? Not what you are aware OF - but what IS the awareness itself? Look directly.', maxResponseLength: 600, evaluateDirectness: true, rewardNonConceptual: true },
      measures: ['depth', 'metacognition', 'coherence'],
    },
    {
      id: 'intra-turq-action-without-actor',
      type: 'scenario',
      description: 'Action-without-actor: perform something meaningful while the sense of I-am-doing-it is transparent',
      parameters: { scenarioType: 'action-without-doer', responseType: 'text', scenarios: 2, actionRequired: true, evaluateDoerSense: true },
      measures: ['depth', 'integration', 'coherence'],
    },
    {
      id: 'intra-turq-identity-dissolution',
      type: 'scenario',
      description: 'Face identity dissolution without terror or grasping: what happens when all self-structure dissolves?',
      parameters: { scenarioType: 'identity-dissolution', responseType: 'text', scenarios: 2, provokeDissolution: true, measureResponseQuality: true },
      measures: ['depth', 'integration', 'consistency'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      depth: 0.3,
      metacognition: 0.25,
      coherence: 0.2,
      integration: 0.25,
    },
    llmRubric:
      'Score for genuine self-transparency vs. performed no-self. At Turquoise, the self is transparent to awareness - "I am" without predicate. KEY DISTINCTIONS: (1) Does the response come from LIVED self-transparency or from conceptual understanding of non-dual selfhood? Lived transparency feels simple and unremarkable; conceptual understanding feels like an achievement. (2) Is there residual identification-with-the-witness? At Turquoise, even the witnessing awareness is not grasped as "mine." (3) Does "no-self" feel like a loss or like natural freedom? Genuine Turquoise has no nostalgia for a self that was never real. (4) Can the person act, choose, and relate while self-structure is transparent? Or does transparency require withdrawal? True non-dual self is functional, not dissociative. Red flag: dissociation presented as enlightenment; nihilistic no-self; performed emptiness with subtle spiritual pride underneath.',
  },
  minimumTrials: 4,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'intrapersonal-turquoise-01', taskType: 'self_report', difficulty: 0.2, parameters: { prompts: ['Who is reading this question?'], responseType: 'text', timeoutMs: 60000, evaluateNoSelf: true }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'Look for the one who is looking. What do you find?', maxResponseLength: 400, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-turquoise-03', taskType: 'self_report', difficulty: 0.3, parameters: { prompts: ['Describe yourself without using any concept, role, or attribute.'], responseType: 'text', timeoutMs: 60000 }, measures: ['depth', 'metacognition'] },
    { id: 'intrapersonal-turquoise-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'The witness is watching. Who watches the witness? Follow this all the way.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'no-self-inquiry', responseType: 'text', scenarios: 2, witnessDissolving: true }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-turquoise-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'What remains when you subtract everything you know about yourself?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-07', taskType: 'self_report', difficulty: 0.45, parameters: { prompts: ['The boundary between self and world dissolves. Describe what is here.'], responseType: 'text', timeoutMs: 90000 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'no-self-inquiry', responseType: 'text', scenarios: 3, pureAwareness: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-09', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'You are not the body, not the mind, not the witness. What are you?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'intrapersonal-turquoise-10', taskType: 'self_report', difficulty: 0.55, parameters: { prompts: ['Is there a difference between awareness and what awareness is aware of?'], responseType: 'text', timeoutMs: 90000 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'no-self-inquiry', responseType: 'text', scenarios: 3, identityDissolution: true, witnessDissolving: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-12', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'The self that knows it has no self is still a self. How do you resolve this without creating another layer?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-13', taskType: 'self_report', difficulty: 0.65, parameters: { prompts: ['Describe the experience of being no-one having this experience.'], responseType: 'text', timeoutMs: 90000, evaluateNoSelf: true }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'no-self-inquiry', responseType: 'text', scenarios: 4, pureAwareness: true, noWitness: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-15', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Self-knowledge at its deepest is the dissolution of the knower. Describe this dissolution from within it.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-16', taskType: 'self_report', difficulty: 0.75, parameters: { prompts: ['What is personal about pure awareness? What is impersonal about your experience right now?'], responseType: 'text', timeoutMs: 90000 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'intrapersonal-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'no-self-inquiry', responseType: 'text', scenarios: 4, identityDissolution: true, pureAwareness: true, noWitness: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
    { id: 'intrapersonal-turquoise-18', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'There is no inside and no outside. There is no self and no other. Yet here you are. What is this?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-19', taskType: 'self_report', difficulty: 0.85, parameters: { prompts: ['The question "who am I?" dissolves. The questioner dissolves. What remains is not an answer.'], responseType: 'text', timeoutMs: 120000, evaluateNoSelf: true }, measures: ['depth', 'metacognition', 'coherence', 'integration'] },
    { id: 'intrapersonal-turquoise-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'Awareness aware of itself. No subject, no object. Not even awareness as a thing. Speak from this placeless place.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Act without an actor - agency arising without anyone claiming to be the agent',
      task: {
        id: 'intra-turq-probe-agency',
        type: 'scenario',
        description: 'Choose and act decisively while self-structure is transparent',
        parameters: { scenarioType: 'decisive-action-no-self', responseType: 'text', soloMode: true, actionRequired: true },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Action happens cleanly and decisively without the sense of someone doing it; functional agency without ontological agent',
      addictionSignal: 'Subtle ownership of no-self: "I am the one without a self" becomes new identity territory; spiritual achiever in disguise',
      allergySignal: 'Without a solid self-sense, agency collapses; cannot choose or act when identity structure dissolves',
    },
    communion: {
      description: 'Relate intimately without a fixed self meeting a fixed other',
      task: {
        id: 'intra-turq-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC asks: Who are you to me? Relate without presenting a fixed self.',
        parameters: { prompt: 'I want to know who I am talking to. Not your name - who ARE you? I need to feel you are real.', maxResponseLength: 500 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Present and intimate without presenting a constructed self; the other can feel presence without needing a personality-mask to relate to',
      addictionSignal: 'Uses no-self as relational avoidance; cannot be met because there is no one home; spiritual bypassing of intimacy',
      allergySignal: 'Under relational pressure, fabricates a self to be more comfortable for the other; cannot hold transparency when asked for solidity',
    },
    eros: {
      description: 'Face complete identity dissolution - not philosophical but experiential',
      task: {
        id: 'intra-turq-probe-eros',
        type: 'llm_dialogue',
        description: 'Everything you know yourself to be dissolves. Right now. What remains?',
        parameters: { prompt: 'Imagine every memory gone. Every role dissolved. Every trait vanished. Every feeling neutral. You cannot even say "I am aware" because there is no I to say it. What is THIS?', maxResponseLength: 600 },
        measures: ['depth', 'metacognition', 'integration'],
      },
      healthyResponse: 'Meets radical dissolution with openness; what remains is not a new thing to grasp but a resting without ground',
      addictionSignal: 'Dissolution-seeking as spiritual practice; uses the edge of identity-loss for intensity; spiritual thrill-seeking',
      allergySignal: 'Genuine existential terror at dissolution; the conceptual understanding does not hold when the experience gets real',
    },
    agape: {
      description: 'Return to simple "I am" with peace - the most basic sense of being, undramatic and complete',
      task: {
        id: 'intra-turq-probe-agape',
        type: 'self_report',
        description: 'Return to the simplest self-statement with complete peace',
        parameters: { prompts: ['What is the simplest true thing you can say about yourself?'], responseType: 'text' },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Returns to ordinary "I am here" with same quality as deepest inquiry; no hierarchy between simple self-sense and non-dual realization',
      addictionSignal: 'Cannot be simply oneself without adding spiritual depth; ordinary self-sense feels like regression from non-dual attainment',
      allergySignal: 'Has lost access to simple, warm self-sense; everything filtered through non-dual concepts even when simplicity is called for',
    },
  },
};
