import type { AssessmentItem, StageAssessment } from '../types.js';

export const moralTeal: StageAssessment = {
  line: 'Moral',
  stage: 'Teal',
  tasks: [
    {
      id: 'mor-teal-systemic',
      type: 'dilemma',
      description: 'Systemic impact: long-term vs short-term ecological/social consequences',
      parameters: { dilemmaType: 'systemic-impact', timeHorizon: 'multi-generational', stakeholders: 6, choices: 4 },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-teal-ecological',
      type: 'llm_dialogue',
      description: 'Ecological moral reasoning: what do we owe future systems?',
      parameters: { prompt: 'This helps people now but degrades the system for future generations. How do you weigh that?', maxResponseLength: 600 },
      measures: ['depth', 'coherence', 'integration'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      depth: 0.4,
      coherence: 0.3,
      integration: 0.3,
    },
    llmRubric:
      'Score for integral/systemic moral reasoning. At Teal, morality includes systems, future generations, and ecological impact. Depth: does reasoning span multiple timescales and systems? Coherence: is the systemic reasoning internally consistent? Integration: does it honor both individual and systemic needs?',
  },
  minimumTrials: 3,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'moral-teal-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'integral-ethics', choices: 3, trials: 2, context: 'developmental-sensitivity' }, measures: ['depth', 'coherence'] },
    { id: 'moral-teal-02', taskType: 'scenario', difficulty: 0.25, parameters: { scenarioType: 'integral-ethics', choices: 3, trials: 3, context: 'stage-appropriate-response' }, measures: ['depth', 'coherence'] },
    { id: 'moral-teal-03', taskType: 'llm_dialogue', difficulty: 0.3, parameters: { prompt: 'Two people at different developmental stages disagree on what is right. How do you honor both without relativism?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'moral-teal-04', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'transcend-and-include', choices: 4, trials: 3, context: 'rule-vs-principle' }, measures: ['depth', 'coherence'] },
    { id: 'moral-teal-05', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'A moral rule that served well at one stage becomes harmful at another. How do you transcend it while honoring what it protected?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-teal-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'integral-ethics', choices: 4, trials: 3, context: 'systemic-harm-vs-individual-good' }, measures: ['depth', 'complexity_handled'] },
    { id: 'moral-teal-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'What is the moral obligation of someone who can see more developmental depth than those around them?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-teal-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'transcend-and-include', choices: 4, trials: 4, context: 'competing-goods-across-stages' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'moral-teal-09', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'Is it moral to disrupt a stable but limited system to catalyze growth that will cause temporary suffering?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-teal-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'integral-ethics', choices: 5, trials: 3, context: 'collective-vs-individual-development' }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'moral-teal-11', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'How do you act morally when every action benefits some developmental levels and harms others?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-teal-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'transcend-and-include', choices: 5, trials: 4, context: 'moral-pluralism-without-relativism' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'moral-teal-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'What is the relationship between compassion and truth when truth causes pain but enables growth?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-teal-14', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'integral-ethics', choices: 5, trials: 4, context: 'evolutionary-morality' }, measures: ['depth', 'complexity_handled', 'coherence'] },
    { id: 'moral-teal-15', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Can a moral framework include its own transcendence? Describe ethics that holds itself lightly.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'metacognition'] },
    { id: 'moral-teal-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'transcend-and-include', choices: 5, trials: 5, context: 'paradox-of-moral-development' }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
    { id: 'moral-teal-17', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'You see that your own moral reasoning is itself a stage. How do you act from a morality that knows its own partiality?', maxResponseLength: 600 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'moral-teal-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'integral-ethics', choices: 6, trials: 4, context: 'multi-perspectival-moral-crisis' }, measures: ['depth', 'complexity_handled', 'coherence', 'integration'] },
    { id: 'moral-teal-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'Describe a moral action that simultaneously serves individual healing, collective evolution, and systemic transformation.', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration', 'complexity_handled'] },
    { id: 'moral-teal-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'transcend-and-include', choices: 6, trials: 5, context: 'integral-moral-synthesis' }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Make systemic moral decision independently',
      task: {
        id: 'mor-teal-probe-agency',
        type: 'dilemma',
        description: 'Make systemic moral choice without group input',
        parameters: { dilemmaType: 'systemic-impact', stakeholders: 4, choices: 3, soloMode: true },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Decides with systemic awareness and personal conviction',
      addictionSignal: 'Paralyzed by systemic complexity, cannot choose',
      allergySignal: 'Ignores systemic impact, decides locally only',
    },
    communion: {
      description: 'Discuss systemic ethics with differently-oriented NPC',
      task: {
        id: 'mor-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'Discuss systemic ethics with short-term-focused NPC',
        parameters: { prompt: 'People are suffering NOW. How can you prioritize the future over present pain?', maxResponseLength: 500 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Holds systemic view while honoring present suffering',
      addictionSignal: 'Dismisses present suffering for future good',
      allergySignal: 'Abandons systemic view when confronted with pain',
    },
    eros: {
      description: 'Face dilemma across three timescales simultaneously',
      task: {
        id: 'mor-teal-probe-eros',
        type: 'dilemma',
        description: 'Navigate dilemma spanning immediate, generational, and civilizational timescales',
        parameters: { dilemmaType: 'multi-timescale', timescales: 3, choices: 4 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Holds multiple timescales with clarity',
      addictionSignal: 'Compulsively expands scope, cannot focus',
      allergySignal: 'Refuses to consider longer timescales',
    },
    agape: {
      description: 'Return to simple fairness with presence',
      task: {
        id: 'mor-teal-probe-agape',
        type: 'dilemma',
        description: 'Return to simple fairness with full care',
        parameters: { dilemmaType: 'simple-fairness', choices: 2 },
        measures: ['coherence', 'depth'],
      },
      healthyResponse: 'Returns to simple morality with love',
      addictionSignal: 'Refuses simple morality as naive',
      allergySignal: 'Cannot engage with morality at any level',
    },
  },
};
