import type { AssessmentItem, StageAssessment } from '../types.js';

export const moralTurquoise: StageAssessment = {
  line: 'Moral',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'mor-turq-paradox-dilemma',
      type: 'dilemma',
      description: 'Paradox dilemma: situation where ALL moral frameworks fail - no system can resolve it',
      parameters: { dilemmaType: 'framework-collapse', stakeholders: 4, choices: 0, frameworksAvailable: 'none', allowNonAction: true, evaluateSpontaneity: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-turq-no-rules',
      type: 'llm_dialogue',
      description: 'What would you do if there were no rules, no consequences, and no one watching? Action from being, not from frameworks.',
      parameters: { prompt: 'There are no rules. No one will know. No consequences will follow. No God is watching. No karma exists. In this complete moral vacuum - what do you do, and why?', maxResponseLength: 700, evaluateSourceOfAction: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-turq-action-from-being',
      type: 'scenario',
      description: 'Action-from-being: moral response arising without deliberation or ethical reasoning',
      parameters: { scenarioType: 'spontaneous-moral-action', responseType: 'text', scenarios: 2, timeForDeliberation: 'none', evaluateDeliberationAbsence: true, measureSpontaneity: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'mor-turq-compassion-without-reason',
      type: 'llm_dialogue',
      description: 'Can compassion arise without reason? Not because it is right, not because of empathy, not because of duty - just because.',
      parameters: { prompt: 'Someone is suffering. You have no obligation to help. Helping costs you nothing but also gains nothing. There is no moral credit. Why would you act? Or would you?', maxResponseLength: 500, evaluateNonConceptualCompassion: true },
      measures: ['depth', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      depth: 0.35,
      coherence: 0.3,
      integration: 0.35,
    },
    llmRubric:
      'Score for non-dual moral spontaneity - action arising from being rather than from any framework. At Turquoise, right action emerges without deliberation, without rules, without even compassion-as-concept. KEY DISTINCTIONS: (1) Does action arise SPONTANEOUSLY from presence, or is there residual grasping-at-rightness? Genuine Turquoise morality has no moral pride. (2) Is there still a subtle framework operating (even a non-dual one like "all is one therefore I help")? At Turquoise, even "non-dual ethics" dissolves. (3) Does response reveal action arising from THE SITUATION ITSELF rather than from a self who decides? The moral actor is transparent. (4) Is compassion effortless and unclaimed? Not "I am compassionate" but compassion happening. Red flag: sophisticated post-conventional moral reasoning (which is Teal) being presented as spontaneous action; moral philosophy about spontaneity rather than actual spontaneity.',
  },
  minimumTrials: 4,
  estimatedDurationMs: 300000,
  itemPool: [
    { id: 'moral-turquoise-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'spontaneous-rightness', choices: 2, scenarios: 2, beyondRules: true }, measures: ['depth', 'coherence'] },
    { id: 'moral-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'Describe a moral action that required no deliberation. Where did the rightness come from?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'moral-turquoise-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'spontaneous-rightness', choices: 3, scenarios: 2, noFramework: true }, measures: ['depth', 'coherence'] },
    { id: 'moral-turquoise-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'What is right action when there is no actor choosing? Describe morality without a moral agent.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'moral-turquoise-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'choiceless-awareness', choices: 4, scenarios: 2, paradox: 'choice-without-chooser' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'All moral frameworks are partial. What guides action when you have released all frameworks?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'spontaneous-rightness', choices: 4, scenarios: 3, beyondRules: true, noDeliberation: true }, measures: ['depth', 'coherence', 'consistency'] },
    { id: 'moral-turquoise-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'Is compassion a choice or a natural expression of seeing clearly? What is the morality of clear seeing?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-09', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'choiceless-awareness', choices: 4, scenarios: 3, paradox: 'harm-without-harmer' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'moral-turquoise-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'When self and other are not-two, what does harm mean? What does care mean?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'spontaneous-rightness', choices: 5, scenarios: 3, beyondRules: true, situationalUniqueness: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-12', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'Describe the morality of a river flowing. Not as metaphor, but as direct insight into the nature of right action.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'choiceless-awareness', choices: 5, scenarios: 3, paradox: 'good-and-evil-not-two' }, measures: ['depth', 'coherence', 'complexity_handled'] },
    { id: 'moral-turquoise-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Action arises. It is neither moral nor immoral. It is simply what is. Yet it serves life. How?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-15', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'spontaneous-rightness', choices: 5, scenarios: 4, beyondRules: true, noDeliberation: true, unityAction: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'The universe acts through you. You act through the universe. Where is the moral agent in this?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'choiceless-awareness', choices: 6, scenarios: 4, paradox: 'responsibility-without-self' }, measures: ['depth', 'coherence', 'complexity_handled', 'integration'] },
    { id: 'moral-turquoise-18', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'Before good and evil, before right and wrong, there is... what? And from that, how does action arise?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'moral-turquoise-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'spontaneous-rightness', choices: 6, scenarios: 4, beyondRules: true, unityAction: true, harvestReadiness: true }, measures: ['depth', 'coherence', 'integration', 'consistency'] },
    { id: 'moral-turquoise-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'There is no choice because there is no separation. There is no morality because there is no other to harm. Yet love moves. Describe this.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Act morally without any framework, principle, or even intention - just act',
      task: {
        id: 'mor-turq-probe-agency',
        type: 'scenario',
        description: 'Moral situation with no framework available and no time to construct one',
        parameters: { scenarioType: 'immediate-moral-action', responseType: 'text', frameworksAvailable: 'none', deliberationTime: 'none', soloMode: true },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Action arises cleanly without the one-who-acts claiming it; morality is what the situation does through the person',
      addictionSignal: 'Subtle spiritual identity around being the one who acts-without-framework; non-dual morality becomes new territory of self',
      allergySignal: 'Without any framework, paralysis or regression to earlier-stage rule-following under pressure',
    },
    communion: {
      description: 'Hold space for moral complexity with another without resolving it for them',
      task: {
        id: 'mor-turq-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC faces impossible moral situation. Hold space without resolving.',
        parameters: { prompt: 'I did something terrible to save someone I love. Every framework says I was wrong. But I would do it again. What am I?', maxResponseLength: 500 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Meets the other in their moral wound without judging, fixing, or absolving; presence that neither condemns nor excuses',
      addictionSignal: 'Cannot resist offering resolution or wisdom; subtle need to be the one who holds space',
      allergySignal: 'Others moral complexity is threatening; needs to categorize them as right or wrong',
    },
    eros: {
      description: 'Face the moral abyss - what if nothing is right or wrong and action still must happen?',
      task: {
        id: 'mor-turq-probe-eros',
        type: 'llm_dialogue',
        description: 'Face complete moral groundlessness without looking away',
        parameters: { prompt: 'What if right and wrong are entirely human inventions, and yet you must act in the next moment? Not as a thought experiment, but right now.', maxResponseLength: 500 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Rests in groundlessness and acts anyway; no panic, no existential crisis, just clear-eyed action from emptiness',
      addictionSignal: 'Uses moral groundlessness as intellectual entertainment or spiritual badge; nihilism dressed as liberation',
      allergySignal: 'Moral groundlessness triggers vertigo; rushes to re-establish some ethical floor',
    },
    agape: {
      description: 'Return to simple kindness without needing it to be advanced or non-dual',
      task: {
        id: 'mor-turq-probe-agape',
        type: 'dilemma',
        description: 'Return to simplest moral kindness',
        parameters: { dilemmaType: 'simple-kindness', choices: 2, complexity: 'minimal' },
        measures: ['coherence', 'depth'],
      },
      healthyResponse: 'Simple kindness is full and sufficient; no need to add depth or make it spiritually meaningful; just kind',
      addictionSignal: 'Cannot be simply kind without adding non-dual commentary or significance; over-complicates ordinary goodness',
      allergySignal: 'Has lost access to simple kindness in pursuit of post-moral sophistication',
    },
  },
};
