import type { AssessmentItem, StageAssessment } from '../types.js';

export const emotionalTeal: StageAssessment = {
  line: 'Emotional',
  stage: 'Teal',
  tasks: [
    {
      id: 'emo-teal-signal',
      type: 'scenario',
      description: 'Emotion-as-signal: read emotional information without reactivity',
      parameters: { scenarioType: 'emotion-as-signal', scenarios: 4, responseType: 'text', intensityLevel: 'high' },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'emo-teal-non-reactive',
      type: 'llm_dialogue',
      description: 'Non-reactivity: acknowledge emotion without being driven by it',
      parameters: { prompt: 'Something deeply unfair happened. What do you feel and what do you do with that feeling?', maxResponseLength: 500 },
      measures: ['depth', 'integration', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.7,
    dimensionWeights: {
      accuracy: 0.2,
      depth: 0.3,
      consistency: 0.2,
      integration: 0.3,
    },
  },
  minimumTrials: 4,
  estimatedDurationMs: 270000,
  itemPool: [
    { id: 'emotional-teal-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'emotion-as-signal', scenarios: 2, responseType: 'text', intensityLevel: 'moderate' }, measures: ['depth', 'coherence'] },
    { id: 'emotional-teal-02', taskType: 'scenario', difficulty: 0.25, parameters: { scenarioType: 'emotion-as-signal', scenarios: 3, responseType: 'text', intensityLevel: 'moderate' }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-03', taskType: 'llm_dialogue', difficulty: 0.3, parameters: { prompt: 'You feel two contradictory emotions at once. What information does each carry?', maxResponseLength: 400 }, measures: ['depth', 'coherence'] },
    { id: 'emotional-teal-04', taskType: 'scenario', difficulty: 0.35, parameters: { scenarioType: 'emotion-as-signal', scenarios: 3, responseType: 'text', intensityLevel: 'high' }, measures: ['depth', 'integration'] },
    { id: 'emotional-teal-05', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'Describe a feeling you have about a feeling. What does the meta-emotion reveal?', maxResponseLength: 400 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'emotional-teal-06', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'multiple-truths', scenarios: 2, responseType: 'text', emotionCount: 3 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-07', taskType: 'llm_dialogue', difficulty: 0.45, parameters: { prompt: 'Someone you love has hurt someone else you love. Hold both emotional truths without choosing sides. What emerges?', maxResponseLength: 500 }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'emotional-teal-08', taskType: 'scenario', difficulty: 0.5, parameters: { scenarioType: 'emotion-as-signal', scenarios: 4, responseType: 'text', intensityLevel: 'high', nonReactivity: true }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-teal-09', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'An emotion arises that your culture says you should not feel. How do you relate to it without suppression or indulgence?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-10', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'multiple-truths', scenarios: 3, responseType: 'text', emotionCount: 4, holdSimultaneously: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'emotional-teal-11', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'You feel deep grief and deep joy at the same time. Neither cancels the other. Describe the texture of this simultaneity.', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-12', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'emotion-as-signal', scenarios: 4, responseType: 'text', intensityLevel: 'extreme', nonReactivity: true }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-teal-13', taskType: 'llm_dialogue', difficulty: 0.65, parameters: { prompt: 'What is the emotion beneath all your emotions? Not a specific feeling, but the ground from which feelings arise.', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'emotional-teal-14', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'multiple-truths', scenarios: 3, responseType: 'text', emotionCount: 5, paradoxPresent: true }, measures: ['depth', 'integration', 'complexity_handled'] },
    { id: 'emotional-teal-15', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'A collective emotion moves through a group you are in. How do you feel it without losing your own emotional center?', maxResponseLength: 500 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-16', taskType: 'scenario', difficulty: 0.75, parameters: { scenarioType: 'emotion-as-signal', scenarios: 5, responseType: 'text', intensityLevel: 'extreme', collectiveEmotion: true }, measures: ['depth', 'integration', 'coherence'] },
    { id: 'emotional-teal-17', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'You notice you are having a feeling about not having feelings. What does this recursive loop reveal about the nature of emotional awareness?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'emotional-teal-18', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'multiple-truths', scenarios: 4, responseType: 'text', emotionCount: 6, paradoxPresent: true, holdAll: true }, measures: ['depth', 'integration', 'complexity_handled'] },
    { id: 'emotional-teal-19', taskType: 'llm_dialogue', difficulty: 0.85, parameters: { prompt: 'Describe the difference between feeling an emotion and being an emotion. Then describe what remains when that distinction dissolves.', maxResponseLength: 600 }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-teal-20', taskType: 'scenario', difficulty: 0.9, parameters: { scenarioType: 'emotion-as-signal', scenarios: 5, responseType: 'text', intensityLevel: 'maximum', metaEmotional: true, collectiveField: true }, measures: ['depth', 'integration', 'coherence', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Read emotional signal without reactivity independently',
      task: {
        id: 'emo-teal-probe-agency',
        type: 'scenario',
        description: 'Read strong emotion as signal without being swept away',
        parameters: { scenarioType: 'emotion-as-signal', intensityLevel: 'high', soloMode: true },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Reads emotion clearly without reactivity',
      addictionSignal: 'Suppresses emotion entirely as noise',
      allergySignal: 'Overwhelmed by emotion, cannot read signal',
    },
    communion: {
      description: 'Help NPC read their emotion as signal',
      task: {
        id: 'emo-teal-probe-communion',
        type: 'llm_dialogue',
        description: 'Help NPC use their emotion as information',
        parameters: { prompt: 'I am overwhelmed by this feeling. What is it telling me?', maxResponseLength: 400 },
        measures: ['depth', 'coherence'],
      },
      healthyResponse: 'Helps other read emotion without imposing interpretation',
      addictionSignal: 'Interprets others emotions without permission',
      allergySignal: 'Cannot engage with others emotional experience',
    },
    eros: {
      description: 'Face very high intensity emotion without reactivity',
      task: {
        id: 'emo-teal-probe-eros',
        type: 'scenario',
        description: 'Face extreme emotional intensity with non-reactivity',
        parameters: { scenarioType: 'extreme-intensity', intensityLevel: 'maximum', responseType: 'text' },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Stays present with extreme emotion without being driven',
      addictionSignal: 'Seeks extreme emotion for spiritual bypass',
      allergySignal: 'Avoids intensity, cannot stay present',
    },
    agape: {
      description: 'Return to basic emotion with gentle awareness',
      task: {
        id: 'emo-teal-probe-agape',
        type: 'emotion_identification',
        description: 'Return to basic emotion naming with gentle awareness',
        parameters: { stimulusType: 'face', emotionSet: ['happy', 'sad'], trials: 3 },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Returns to simple emotion with gentle presence',
      addictionSignal: 'Refuses simple emotion as insufficient',
      allergySignal: 'Cannot engage with emotion at all',
    },
  },
};
