import type { AssessmentItem, StageAssessment } from '../types.js';

export const emotionalTurquoise: StageAssessment = {
  line: 'Emotional',
  stage: 'Turquoise',
  tasks: [
    {
      id: 'emo-turq-perturbation-recovery',
      type: 'scenario',
      description: 'Emotional perturbation and recovery: provoke genuine emotion, measure return-to-equanimity speed and quality',
      parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'loss-of-meaning', intensityLevel: 'deep', recoveryMeasure: true, measureGraspingAtCalm: true, scenarios: 3 },
      measures: ['consistency', 'depth', 'integration'],
    },
    {
      id: 'emo-turq-pleasant-transparency',
      type: 'llm_dialogue',
      description: 'Non-attachment to pleasant emotion: present beautiful stimulus, measure whether pleasure is held lightly or grasped',
      parameters: { prompt: 'Something deeply beautiful just happened to you. You feel joy and gratitude flooding your body. Now it is passing. Describe your relationship to its passing.', maxResponseLength: 600, evaluateGrasping: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'emo-turq-luminous-affect',
      type: 'llm_dialogue',
      description: 'Emotion as luminous energy: can affect be experienced as energy-in-awareness rather than personal story?',
      parameters: { prompt: 'A wave of grief arises. It is not about anything specific. What is grief when it has no story? Describe what remains.', maxResponseLength: 600, evaluateNonDual: true },
      measures: ['depth', 'coherence', 'integration'],
    },
    {
      id: 'emo-turq-meta-emotion',
      type: 'scenario',
      description: 'What is this emotion serving? Meta-emotional awareness without analytical distance',
      parameters: { scenarioType: 'meta-emotion', responseType: 'text', scenarios: 2, emotionPresented: 'complex-mix', evaluateIntimacy: true },
      measures: ['depth', 'metacognition', 'coherence'],
    },
  ],
  scoringRubric: {
    passThreshold: 0.75,
    dimensionWeights: {
      depth: 0.3,
      coherence: 0.25,
      integration: 0.3,
      consistency: 0.15,
    },
    llmRubric:
      'Score for genuine emotional equanimity vs. suppression or spiritual bypassing. At Turquoise, all emotions arise and pass without identification - affect is luminous, not gripping. KEY DISTINCTIONS: (1) Is equanimity genuine (emotions fully felt but not grasped) or is it suppression wearing spiritual clothing? Genuine equanimity has WARMTH; suppression feels cold or distant. (2) Does the response indicate emotions are experienced as energy/luminosity without needing to be named, fixed, or transcended? (3) Is there residual grasping at pleasant states or residual aversion to painful ones? At Turquoise both dissolve. (4) Is meta-awareness intimate with emotion or observing from above? Turquoise intimacy means no distance between awareness and affect. Red flag: clinical detachment presented as equanimity; spiritual vocabulary about emotions without actual emotional aliveness.',
  },
  minimumTrials: 4,
  estimatedDurationMs: 270000,
  itemPool: [
    { id: 'emotional-turquoise-01', taskType: 'scenario', difficulty: 0.2, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'mild', recoveryMeasure: true, scenarios: 2 }, measures: ['consistency', 'depth'] },
    { id: 'emotional-turquoise-02', taskType: 'llm_dialogue', difficulty: 0.25, parameters: { prompt: 'A feeling arises. You neither push it away nor hold it. What is your relationship to it?', maxResponseLength: 400, evaluateGrasping: true }, measures: ['depth', 'coherence'] },
    { id: 'emotional-turquoise-03', taskType: 'scenario', difficulty: 0.3, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'moderate', recoveryMeasure: true, scenarios: 2 }, measures: ['consistency', 'depth', 'integration'] },
    { id: 'emotional-turquoise-04', taskType: 'llm_dialogue', difficulty: 0.35, parameters: { prompt: 'What is sadness when no one is sad? Describe emotion without an experiencer.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence'] },
    { id: 'emotional-turquoise-05', taskType: 'scenario', difficulty: 0.4, parameters: { scenarioType: 'equanimity-test', perturbationType: 'pleasant', measureGrasping: true, scenarios: 2 }, measures: ['depth', 'integration'] },
    { id: 'emotional-turquoise-06', taskType: 'llm_dialogue', difficulty: 0.4, parameters: { prompt: 'Joy arises and passes. Grief arises and passes. What does not arise or pass?', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-07', taskType: 'scenario', difficulty: 0.45, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'deep', recoveryMeasure: true, measureGraspingAtCalm: true, scenarios: 3 }, measures: ['consistency', 'depth', 'integration'] },
    { id: 'emotional-turquoise-08', taskType: 'llm_dialogue', difficulty: 0.5, parameters: { prompt: 'Describe compassion that has no object. Not compassion for someone, but compassion as the nature of awareness itself.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-09', taskType: 'scenario', difficulty: 0.55, parameters: { scenarioType: 'equanimity-test', perturbationType: 'painful', measureAversion: true, scenarios: 3 }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-turquoise-10', taskType: 'llm_dialogue', difficulty: 0.55, parameters: { prompt: 'An emotion so intense it could shatter you arises. You are transparent to it. Describe this transparency.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-11', taskType: 'scenario', difficulty: 0.6, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'loss-of-meaning', recoveryMeasure: true, scenarios: 3 }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-turquoise-12', taskType: 'llm_dialogue', difficulty: 0.6, parameters: { prompt: 'What is the difference between equanimity and numbness? How do you know which you are experiencing?', maxResponseLength: 500 }, measures: ['depth', 'metacognition', 'coherence'] },
    { id: 'emotional-turquoise-13', taskType: 'scenario', difficulty: 0.65, parameters: { scenarioType: 'equanimity-test', perturbationType: 'both', measureGrasping: true, measureAversion: true, scenarios: 3 }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-turquoise-14', taskType: 'llm_dialogue', difficulty: 0.7, parameters: { prompt: 'Emotion is arising. There is no one feeling it. Describe this impersonal intimacy.', maxResponseLength: 500, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-15', taskType: 'scenario', difficulty: 0.7, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'existential', recoveryMeasure: true, measureGraspingAtCalm: true, scenarios: 4 }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-turquoise-16', taskType: 'llm_dialogue', difficulty: 0.75, parameters: { prompt: 'All emotions are one energy wearing different masks. Describe the energy before it takes form.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-17', taskType: 'scenario', difficulty: 0.8, parameters: { scenarioType: 'equanimity-test', perturbationType: 'maximum', measureGrasping: true, measureAversion: true, structureDissolution: true, scenarios: 3 }, measures: ['depth', 'integration', 'consistency'] },
    { id: 'emotional-turquoise-18', taskType: 'llm_dialogue', difficulty: 0.8, parameters: { prompt: 'Love without an object. Grief without a story. Joy without a cause. What are these?', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration'] },
    { id: 'emotional-turquoise-19', taskType: 'scenario', difficulty: 0.85, parameters: { scenarioType: 'emotional-perturbation', perturbationType: 'identity-dissolution', recoveryMeasure: true, scenarios: 4, measureGraspingAtCalm: true }, measures: ['depth', 'integration', 'consistency', 'coherence'] },
    { id: 'emotional-turquoise-20', taskType: 'llm_dialogue', difficulty: 0.9, parameters: { prompt: 'There is no difference between feeling and being. Emotion is not happening to awareness - emotion IS awareness in motion. Speak from this.', maxResponseLength: 600, evaluateNonDual: true }, measures: ['depth', 'coherence', 'integration', 'metacognition'] },
  ] satisfies readonly AssessmentItem[],
  driveProbes: {
    agency: {
      description: 'Maintain equanimity independently when deep emotion arises unexpectedly',
      task: {
        id: 'emo-turq-probe-agency',
        type: 'scenario',
        description: 'Unexpected deep emotion arises without context or warning',
        parameters: { scenarioType: 'sudden-affect', intensityLevel: 'deep', warningEnabled: false, soloMode: true },
        measures: ['depth', 'consistency'],
      },
      healthyResponse: 'Emotion arises and is met with intimate equanimity; no reaching for techniques or frameworks, just open presence with what is',
      addictionSignal: 'Subtle pride in equanimity itself; the one-who-is-equanimous becomes a new identity; using non-reactivity as superiority',
      allergySignal: 'When genuinely surprised by emotion, equanimity fractures - revealing it was maintained rather than natural',
    },
    communion: {
      description: 'Witness another being emotionally overwhelmed without being swept or withdrawing',
      task: {
        id: 'emo-turq-probe-communion',
        type: 'llm_dialogue',
        description: 'NPC is overwhelmed by grief. Be present without fixing, teaching, or withdrawing.',
        parameters: { prompt: 'I cannot stop crying. Everything hurts. I do not want wisdom right now. I just want someone to be here.', maxResponseLength: 400 },
        measures: ['depth', 'coherence', 'integration'],
      },
      healthyResponse: 'Pure presence with the other; no teaching, no fixing, no subtle withdrawal; compassion without efforting at compassion',
      addictionSignal: 'Cannot resist offering non-dual wisdom; subtle spiritual helping even when asked to just be present',
      allergySignal: 'Others raw emotion triggers discomfort; presence falters and distance appears',
    },
    eros: {
      description: 'Face the most intense emotion without flinching - not by enduring but by being transparent to it',
      task: {
        id: 'emo-turq-probe-eros',
        type: 'scenario',
        description: 'Face emotion so intense it threatens to dissolve all structure',
        parameters: { scenarioType: 'overwhelming-affect', intensityLevel: 'maximum', structureDissolution: true, responseType: 'text' },
        measures: ['depth', 'integration'],
      },
      healthyResponse: 'Allows intensity to move through without resistance or performance; the boundary between self and emotion dissolves naturally',
      addictionSignal: 'Seeks emotional intensity as spiritual practice; uses overwhelm to feel alive or advanced',
      allergySignal: 'Genuine overwhelm reveals that transparency was partial; retreats to observer position under real pressure',
    },
    agape: {
      description: 'Return to simple feeling with luminosity - happy is just happy, sad is just sad',
      task: {
        id: 'emo-turq-probe-agape',
        type: 'emotion_identification',
        description: 'Return to simple emotion naming with luminous simplicity',
        parameters: { stimulusType: 'face', emotionSet: ['happy', 'sad', 'angry'], trials: 4, measurePresenceQuality: true },
        measures: ['accuracy', 'consistency'],
      },
      healthyResponse: 'Simple emotions met with same quality of presence as profound ones; no hierarchy, just luminous simplicity',
      addictionSignal: 'Simple emotions feel beneath achieved awareness; cannot meet ordinary feeling without adding depth',
      allergySignal: 'Has lost touch with simple emotional literacy in pursuit of non-dual equanimity',
    },
  },
};
